import { documentShell, field } from "@/lib/documents/templates/layout";
import { displayText, escapeHtml, formatBkkDateTime } from "@/lib/documents/render";
import type { DocumentSourceSnapshot } from "@/lib/documents/types";

export function renderWorkOrderHtml(snapshot: DocumentSourceSnapshot, documentCode: string): string {
  const appointment = snapshot.appointment.startsAt && snapshot.appointment.endsAt ? `${formatBkkDateTime(snapshot.appointment.startsAt)} – ${formatBkkDateTime(snapshot.appointment.endsAt)}` : "ไม่ระบุ";
  const itemRows = snapshot.items.map((item) => `<tr><td>${displayText(item.category)}</td><td>${displayText(item.sku)}</td><td>${displayText(item.itemName)}</td><td>${displayText(item.specification)}</td><td class="number">${item.plannedQty}</td><td>${displayText(item.unit)}</td></tr>`).join("") || `<tr><td colspan="6">ไม่พบรายการที่ยืนยัน</td></tr>`;
  const body = `<section class="grid">${field("เลขงาน", snapshot.jobNo)}${field("เลขบิล", snapshot.job.billNo)}${field("ลูกค้า", snapshot.job.customerName)}${field("โทรศัพท์", snapshot.job.customerPhone)}${field("ที่อยู่หน้างาน", snapshot.job.address)}${field("สถานะต้นทาง", snapshot.workOrder.status)}${field("สินค้า/ขอบเขตงาน", snapshot.job.productName)}${field("นัดหมาย", appointment)}${field("ทีมรับผิดชอบ", snapshot.appointment.teamName)}${field("จุดอ้างอิงแผนที่", snapshot.job.locationUrl)}</section><h2>สรุปสำรวจหน้างาน</h2><section class="grid">${field("พื้นที่", snapshot.survey.areaSqm === null ? null : `${snapshot.survey.areaSqm} ตร.ม.`)}${field("สภาพพื้น", snapshot.survey.floorCondition)}${field("พื้นที่เปียก", snapshot.survey.wetZone)}${field("รูปสำรวจ", `${snapshot.survey.photoCount} รูป`)}</section><div class="note">${displayText(snapshot.survey.notes ?? "ไม่มีหมายเหตุเพิ่มเติม")}</div><h2>รายการที่ยืนยันเพื่อดำเนินงาน</h2><table><thead><tr><th>หมวด</th><th>SKU</th><th>รายการ</th><th>Specification</th><th class="number">จำนวน</th><th>หน่วย</th></tr></thead><tbody>${itemRows}</tbody></table>${snapshot.workOrder.note ? `<div class="note"><b>หมายเหตุใบสั่งงาน:</b> ${escapeHtml(snapshot.workOrder.note)}</div>` : ""}<section class="signatures"><div class="signature">จัดทำ<br>__________________</div><div class="signature">ตรวจทาน<br>__________________</div><div class="signature">อนุมัติ<br>__________________</div><div class="signature">ผู้รับงาน<br>__________________</div></section>`;
  return documentShell({ title: "ใบสั่งงานติดตั้ง / Work Order", documentCode, revision: snapshot.workOrder.revision, sourceUpdatedAt: snapshot.sourceUpdatedAt, body });
}
