"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { toast } from "sonner";
import { createClient } from "@/lib/supabase/client";
import TechnicianAssignmentButton from "@/components/appointments/technician-assignment";
import type { FloorTechnician, TechnicianAssignment } from "@/lib/technicians";
import { WORK_ITEM_CATEGORY_LABELS, WORK_ORDER_STATUS_LABELS, type WorkOrder, type WorkOrderItem, workOrderStatusClass } from "@/lib/work-orders";

interface Team { id: string; name: string }
interface Job { job_no: string; source: string | null; bill_no: string | null; customer_name: string | null; customer_phone: string | null; address: string | null; location_url: string | null; product_name: string | null; status: string | null; flag_note: string | null; survey_data: string | null; site_photos: string[] | null }
interface Appointment { id: string; job_id: string | null; tech_id: string | null; slot_start: string; slot_end: string; status: string; notes: string | null; requirement: string | null; job: Job | Job[] | null }
type TechWithToken = FloorTechnician & { personal_token: string };

function dateTime(iso: string) { return new Date(iso).toLocaleString("th-TH", { weekday: "short", day: "numeric", month: "short", hour: "2-digit", minute: "2-digit", timeZone: "Asia/Bangkok" }); }
function jobOf(appointment: Appointment) { return Array.isArray(appointment.job) ? appointment.job[0] ?? null : appointment.job; }
function surveySummary(value: string | null) { try { const data = value ? JSON.parse(value) : {}; return [data.areaSqm ? `${data.areaSqm} ตร.ม.` : "", data.floorCondition || "", Array.isArray(data.cutTypes) ? data.cutTypes.join(", ") : ""].filter(Boolean).join(" · "); } catch { return ""; } }

export default function OperationsPage() {
  const supabase = useMemo(() => createClient(), []);
  const [appointments, setAppointments] = useState<Appointment[]>([]); const [teams, setTeams] = useState<Team[]>([]); const [technicians, setTechnicians] = useState<TechWithToken[]>([]);
  const [assignments, setAssignments] = useState<TechnicianAssignment[]>([]); const [orders, setOrders] = useState<WorkOrder[]>([]); const [items, setItems] = useState<WorkOrderItem[]>([]);
  const [loading, setLoading] = useState(true); const [tab, setTab] = useState<"decision" | "active">("decision");
  const load = useCallback(async () => {
    setLoading(true); const since = new Date(Date.now() - 7 * 86400000).toISOString();
    const [appointmentResult, teamResult, technicianResult, assignmentResult, orderResult] = await Promise.all([
      supabase.from("appointments").select("id,job_id,tech_id,slot_start,slot_end,status,notes,requirement,job:install_jobs(job_no,source,bill_no,customer_name,customer_phone,address,location_url,product_name,status,flag_note,survey_data,site_photos)").neq("status", "cancelled").gte("slot_end", since).order("slot_start"),
      supabase.from("tech_teams").select("id,name").eq("is_active", true).order("name"),
      supabase.from("floor_technicians").select("id,team_id,name,phone,is_team_lead,is_active,created_at,updated_at,personal_token").eq("is_active", true).order("name"),
      supabase.from("appointment_technicians").select("*").eq("is_active", true).order("assigned_at"),
      supabase.from("floor_work_orders").select("*").neq("status", "cancelled").order("updated_at", { ascending: false }),
    ]);
    const error = appointmentResult.error ?? teamResult.error ?? technicianResult.error ?? assignmentResult.error ?? orderResult.error; if (error) toast.error(`โหลดงานไม่ครบ: ${error.message}`);
    const orderRows = (orderResult.data ?? []) as WorkOrder[]; setAppointments((appointmentResult.data ?? []) as unknown as Appointment[]); setTeams((teamResult.data ?? []) as Team[]); setTechnicians((technicianResult.data ?? []) as TechWithToken[]); setAssignments((assignmentResult.data ?? []) as TechnicianAssignment[]); setOrders(orderRows);
    if (orderRows.length) { const { data } = await supabase.from("floor_work_order_items").select("*").in("work_order_id", orderRows.map((row) => row.id)).order("sort_order"); setItems((data ?? []) as WorkOrderItem[]); } else setItems([]); setLoading(false);
  }, [supabase]);
  useEffect(() => { void load(); }, [load]);
  async function copyLink(token: string) { await navigator.clipboard.writeText(`${window.location.origin}/work/${token}`); toast.success("คัดลอกลิงก์ช่างแล้ว"); }
  const filtered = appointments.filter((appointment) => { const order = orders.find((row) => row.appointment_id === appointment.id); return tab === "decision" ? !order || ["head_review", "returned_sales"].includes(order.status) : Boolean(order && !["head_review", "returned_sales", "closed"].includes(order.status)); });
  const decisionCount = appointments.filter((appointment) => { const order = orders.find((row) => row.appointment_id === appointment.id); return !order || ["head_review", "returned_sales"].includes(order.status); }).length;

  return <div className="mx-auto max-w-7xl"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="text-xs font-semibold uppercase tracking-wider text-blue-600">หัวหน้าช่าง</div><h1 className="mt-1 text-2xl font-bold text-slate-950">ศูนย์ตัดสินใจและใบสั่งงาน</h1><p className="mt-1 text-sm text-slate-500">ตรวจข้อมูลเต็ม → จ่ายช่าง → สร้างรายการวัสดุ/อุปกรณ์ → ส่งให้คลัง</p></div><button onClick={() => void load()} className="rounded-xl border bg-white px-4 py-2 text-sm">รีเฟรช</button></div>
    <div className="mt-6 flex rounded-xl bg-slate-100 p-1 sm:w-fit"><button onClick={() => setTab("decision")} className={`flex-1 rounded-lg px-4 py-2 text-sm ${tab === "decision" ? "bg-white font-medium shadow-sm" : "text-slate-500"}`}>ต้องตัดสินใจ ({decisionCount})</button><button onClick={() => setTab("active")} className={`flex-1 rounded-lg px-4 py-2 text-sm ${tab === "active" ? "bg-white font-medium shadow-sm" : "text-slate-500"}`}>กำลังดำเนินงาน</button></div>
    <div className="mt-5 space-y-4">{loading ? <div className="rounded-2xl border bg-white p-10 text-center text-slate-400">กำลังโหลด…</div> : null}{!loading && !filtered.length ? <div className="rounded-2xl border bg-white p-10 text-center text-slate-400">ไม่มีงานในรายการนี้</div> : null}{filtered.map((appointment) => {
      const job = jobOf(appointment); const order = orders.find((row) => row.appointment_id === appointment.id); const orderItems = items.filter((row) => row.work_order_id === order?.id); const activeAssignments = assignments.filter((row) => row.appointment_id === appointment.id && row.is_active); const survey = surveySummary(job?.survey_data ?? null); const readyData = Boolean(job?.customer_name && job.customer_phone && (job.address || job.location_url) && (job.product_name || appointment.requirement));
      return <article key={appointment.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b bg-slate-50/60 p-5"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold text-slate-950">{job?.customer_name || appointment.job_id || "งานติดตั้ง"}</h2><span className={`rounded px-2 py-0.5 text-[11px] ${job?.source === "bbps" ? "bg-orange-100 text-orange-700" : "bg-blue-100 text-blue-700"}`}>{job?.source === "bbps" ? "BBPS" : "ขายตรง"}</span></div><p className="mt-1 text-sm text-slate-500">{dateTime(appointment.slot_start)}–{new Date(appointment.slot_end).toLocaleTimeString("th-TH", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Bangkok" })} · {teams.find((team) => team.id === appointment.tech_id)?.name || "ยังไม่ระบุทีม"}</p><p className="mt-1 text-xs text-slate-400">#{job?.job_no || "—"}{job?.bill_no ? ` · บิล ${job.bill_no}` : ""}</p></div>{order ? <span className={`h-fit rounded-full px-3 py-1.5 text-xs font-medium ${workOrderStatusClass(order.status)}`}>{WORK_ORDER_STATUS_LABELS[order.status]}</span> : null}</div></div>
        <div className="grid gap-4 p-5 lg:grid-cols-[1.25fr_1fr]"><div className="space-y-3"><div className={`rounded-xl border p-4 ${readyData ? "border-emerald-200 bg-emerald-50/40" : "border-amber-200 bg-amber-50"}`}><div className="flex justify-between"><h3 className="font-semibold text-slate-900">ข้อมูลที่ต้องตัดสินใจ</h3><span className="text-xs">{readyData ? "✓ ข้อมูลหลักครบ" : "! ข้อมูลไม่ครบ"}</span></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><div><span className="text-slate-400">โทร:</span> {job?.customer_phone || "—"}</div><div><span className="text-slate-400">สถานที่:</span> {job?.address || job?.location_url || "—"}</div><div><span className="text-slate-400">สินค้า:</span> {job?.product_name || appointment.requirement || "—"}</div><div><span className="text-slate-400">สำรวจ:</span> {survey || "ยังไม่มีรายละเอียด"}</div><div><span className="text-slate-400">รูปหน้างาน:</span> {job?.site_photos?.length || 0} รูป</div><div><span className="text-slate-400">หมายเหตุ:</span> {appointment.notes || "—"}</div></div></div>{orderItems.length ? <div className="rounded-xl border border-blue-100 bg-blue-50/50 p-4"><h3 className="text-sm font-semibold text-blue-950">วัสดุและอุปกรณ์ {orderItems.length} รายการ</h3><div className="mt-2 space-y-1 text-xs text-blue-800">{orderItems.slice(0, 5).map((item) => <div key={item.id}>{WORK_ITEM_CATEGORY_LABELS[item.category]} · {item.item_name} · {item.planned_qty} {item.unit}{item.actual_qty != null ? ` (หยิบจริง ${item.actual_qty})` : ""}</div>)}{orderItems.length > 5 ? <div>และอีก {orderItems.length - 5} รายการ</div> : null}</div></div> : null}</div>
          <div className="space-y-3"><div className="rounded-xl border p-4"><div className="flex items-start justify-between gap-2"><div><h3 className="text-sm font-semibold">ช่างรายบุคคล</h3><p className="mt-1 text-xs text-slate-500">กำหนดหัวหน้าทีมก่อนยืนยันใบสั่งงาน</p></div><TechnicianAssignmentButton appointmentId={appointment.id} appointmentTeamId={appointment.tech_id} jobNo={appointment.job_id} teams={teams} technicians={technicians} assignments={assignments} onChanged={() => void load()} /></div><div className="mt-3 space-y-2">{activeAssignments.map((assignment) => { const tech = technicians.find((row) => row.id === assignment.technician_id); return <div key={assignment.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-2 text-xs"><span>{tech?.name || "ช่าง"}{assignment.is_lead ? " ★ หัวหน้า" : ""} · {assignment.acknowledged_at ? "รับทราบแล้ว" : assignment.first_opened_at ? "เปิดแล้ว" : "ยังไม่เปิด"}</span>{tech?.personal_token ? <button onClick={() => void copyLink(tech.personal_token)} className="rounded bg-blue-600 px-2 py-1 text-white">คัดลอกลิงก์</button> : null}</div>; })}{!activeAssignments.length ? <p className="text-xs text-amber-600">ยังไม่ได้จ่ายงานรายบุคคล</p> : null}</div></div><Link href={`/orders/${encodeURIComponent(job?.job_no || appointment.job_id || "")}`} className="block w-full rounded-xl bg-blue-600 py-3 text-center text-sm font-semibold text-white">เปิดใบสั่งงานฉบับเต็ม</Link></div></div>
      </article>;
    })}</div>
  </div>;
}
