import Link from "next/link";

const FLOW = [
  { owner: "ฝ่ายขาย / BBPS", action: "เปิดบิลหรือส่งข้อมูลต้นทาง", status: "รอหัวหน้าช่างตรวจ", href: "/sales-queue" },
  { owner: "หัวหน้าช่าง", action: "ตรวจงาน จ่ายช่าง ระบุ SKU และจำนวน", status: "รอคลังรับงาน", href: "/operations" },
  { owner: "คลัง", action: "รับงาน หยิบของจริง และแนบรูป", status: "รอติดตั้ง", href: "/warehouse" },
  { owner: "ทีมช่าง", action: "รับทราบ ติดตั้ง ส่งรูป เศษ และลายเซ็น", status: "รอ CS โทรประเมิน", href: "/appointments" },
  { owner: "CS", action: "โทรประเมิน บันทึกคะแนน และปิดงาน", status: "ปิดงานแล้ว", href: "/cs-tracking" },
] as const;

const DEPARTMENTS = [
  { icon: "🧾", title: "ฝ่ายขาย — เปิดงานให้พร้อม", href: "/sales-queue", label: "ไปหน้าจองคิว", goal: "ทำให้หัวหน้าช่างตัดสินใจได้โดยไม่ต้องตามข้อมูลซ้ำ", steps: ["เลือกวัน เวลา และทีมช่าง", "กรอกลูกค้า เบอร์โทร สถานที่ และลิงก์ Google Maps", "กรอกสินค้า/สเปก พื้นที่ เงื่อนไขหน้างาน และแนบรูปถ้ามี", "กด บันทึก / เปิดบิล เพื่อส่งงานเข้ารอตรวจ"], result: "สถานะ ‘รอหัวหน้าช่างตรวจ’ พร้อมข้อมูลใช้ตัดสินใจ", exception: "งานขายตรง: แก้ใน FloorNow แล้วส่งตรวจใหม่ · งาน BBPS: แก้ใน BBPS CRM ต้นทาง แล้วรอ Sync กลับ" },
  { icon: "👷", title: "หัวหน้าช่าง — ออกใบสั่งงาน", href: "/operations", label: "ไปหน้าต้องตัดสินใจ", goal: "เปลี่ยนข้อมูลขายเป็นแผนติดตั้งและรายการที่คลังหยิบได้จริง", steps: ["เปิดงานและตรวจลูกค้า สถานที่ รูปสำรวจ และวันนัด", "กำหนดช่างรายบุคคล และเลือกหัวหน้าทีม 1 คน", "เพิ่มรายการวัสดุ: เลือก SKU จำนวนตามแผน หน่วย และหมายเหตุ", "กด ยืนยันใบสั่งงาน เพื่อส่งคลัง"], result: "สถานะ ‘รอคลังรับงาน’ และมีใบสั่งงานกลาง", exception: "ข้อมูลไม่พอ: กด ส่งกลับฝ่ายขาย พร้อมเหตุผลชัดเจน; ห้ามแก้ข้อมูล BBPS แทนระบบต้นทาง" },
  { icon: "📦", title: "คลัง — ยืนยันของจริง", href: "/warehouse", label: "ไปหน้าเตรียมสินค้า", goal: "ให้ช่างรู้ว่าของใดพร้อมและหยิบจริงจำนวนเท่าไร", steps: ["เปิดงานที่ รอคลังรับงาน แล้วกด รับงาน", "หยิบของตามรายการในใบสั่งงาน", "บันทึกจำนวนที่หยิบจริงให้ครบทุกบรรทัด", "แนบรูปสินค้า แล้วกด เตรียมเสร็จ"], result: "สถานะ ‘รอติดตั้ง’ พร้อมจำนวนจริงและรูปหลักฐาน", exception: "หลังติดตั้ง ตรวจรับเศษจากหน้า ตรวจรับเศษ เพื่อรับเข้า/ตีกลับเศษ" },
  { icon: "🛠️", title: "ทีมช่าง — ทำงานและเก็บหลักฐาน", href: "/appointments", label: "ไปปฏิทินทีม", goal: "ให้ลูกค้าและทุกฝ่ายเห็นความคืบหน้าที่ตรวจสอบได้", steps: ["เปิดลิงก์งานส่วนตัวและกด รับทราบงาน", "วันทำงาน หัวหน้าทีมกด รับงานติดตั้ง พร้อมจำนวนแผ่นที่หยิบจริง", "อัปเดต เดินทาง → ถึงหน้างาน → กำลังติดตั้ง → ติดตั้งเสร็จ พร้อมรูป", "บันทึกเศษหรือระบุว่าไม่มีเศษ แล้วให้ลูกค้าเซ็นรับงาน"], result: "สถานะ ‘รอ CS โทรประเมิน’ พร้อมรูป รายงานเศษ และลายเซ็น", exception: "ถ้าหน้างานเปลี่ยน ให้บันทึกหมายเหตุและรูปในงานเดิม ไม่สร้างตั๋วซ้ำ" },
  { icon: "📞", title: "CS — ประเมินและปิดงาน", href: "/cs-tracking", label: "ไปหน้า CS รอติดตาม", goal: "บันทึกเสียงลูกค้าและปิดวงจรงาน", steps: ["เปิดงานสถานะ รอ CS โทรประเมิน", "โทรลูกค้าและบันทึกคะแนน/ข้อเสนอแนะ", "กดบันทึกและปิดงาน"], result: "สถานะ ‘ปิดงานแล้ว’ และข้อมูลไปยังรายงานคุณภาพ", exception: "หากร้องเรียน ให้บันทึกรายละเอียดเพื่อให้ทีมย้อนดูหลักฐานจากใบงานเดียวกัน" },
  { icon: "📈", title: "ผู้บริหาร — แก้คอขวด", href: "/exec", label: "ไปภาพรวมผู้บริหาร", goal: "ติดตามงานทั้งบริษัทจากสถานะใบสั่งงานจริง", steps: ["ดู Pipeline สถานะงานติดตั้งด้านล่างของหน้า", "กดสถานะเพื่อเข้าไปหน้าฝ่ายที่ต้องทำงานต่อ", "ใช้ Lead time งานค้าง และ CSAT เพื่อกำหนดผู้รับผิดชอบ"], result: "เจ้าของงานรู้ว่าต้องทำอะไร ที่หน้าไหน", exception: "ภาพรวมผู้บริหารใช้ติดตาม ไม่ใช่หน้าสำหรับเปลี่ยนสถานะ" },
] as const;

const STATUS = [
  ["รอหัวหน้าช่างตรวจ", "ฝ่ายขาย / BBPS", "หัวหน้าช่าง", "ต้องตัดสินใจ"], ["ส่งกลับต้นทาง", "หัวหน้าช่าง", "ฝ่ายขาย หรือ BBPS", "จองคิว / BBPS CRM"], ["รอคลังรับงาน", "หัวหน้าช่าง", "คลัง", "เตรียมสินค้า"], ["กำลังเตรียมสินค้า", "คลัง", "คลัง", "เตรียมสินค้า"], ["รอติดตั้ง", "คลัง", "ทีมช่าง", "ปฏิทินทีม / ลิงก์ช่าง"], ["กำลังติดตั้ง", "หัวหน้าทีม", "ทีมช่าง", "ลิงก์ช่าง"], ["รอ CS โทรประเมิน", "ทีมช่าง", "CS", "CS รอติดตาม"], ["ปิดงานแล้ว", "CS", "ทุกฝ่ายดูได้", "ใบสั่งงาน / ภาพรวม"],
] as const;

const RCAI = [
  ["เปิดบิล / จองคิว", "ฝ่ายขาย", "ฝ่ายขาย", "หัวหน้าช่าง", "คลัง · ทีมช่าง · CS"],
  ["รับข้อมูล BBPS และส่งเข้าตรวจ", "BBPS CRM", "ฝ่ายขาย / BBPS", "หัวหน้าช่าง", "คลัง · ทีมช่าง"],
  ["ตรวจความพร้อมและส่งกลับ", "หัวหน้าช่าง", "หัวหน้าช่าง", "ฝ่ายขาย / BBPS", "คลัง · ทีมช่าง"],
  ["กำหนด SKU รายการ และช่าง", "หัวหน้าช่าง", "หัวหน้าช่าง", "คลัง", "ฝ่ายขาย · ทีมช่าง"],
  ["หยิบและเตรียมสินค้า", "คลัง", "คลัง", "หัวหน้าช่าง", "ทีมช่าง · ฝ่ายขาย"],
  ["รับงานและอัปเดตหน้างาน", "หัวหน้าทีมช่าง", "หัวหน้าทีมช่าง", "หัวหน้าช่าง", "ฝ่ายขาย · CS · ลูกค้า"],
  ["รายงานเศษและลูกค้าเซ็นรับ", "หัวหน้าทีมช่าง", "หัวหน้าทีมช่าง", "หัวหน้าช่าง", "คลัง · CS · ฝ่ายขาย"],
  ["โทรประเมินและปิดงาน", "CS", "CS", "CS", "ทุกฝ่าย · ผู้บริหาร"],
] as const;

const PAGE_MAP = [
  ["ฝ่ายขาย", "/sales-queue — จองคิว / เปิดบิล", "/tech-queue — ดูคิวและโหลดงานช่าง", "/share/queue — ดูสถานะ/แก้ข้อมูลที่จอง"],
  ["หัวหน้าช่าง", "/operations — ตรวจ ตีกลับ ยืนยันใบสั่งงาน", "/appointments — ดูตารางและโหลดงานรายช่าง", "/technicians — จัดการช่าง/PIN/ลิงก์งาน"],
  ["คลัง", "/warehouse — รับงาน เตรียมของ จำนวนจริง และรูป", "/remnants — ตรวจรับเศษ", "/orders — เปิดดูใบสั่งงาน"],
  ["ทีมช่าง", "/work/[ลิงก์งาน] — รับทราบ อัปเดตสถานะ รูป เศษ ลายเซ็น", "ลิงก์มาจากหัวหน้าช่าง", "—"],
  ["CS", "/cs-tracking — โทรประเมินและปิดงาน", "/dashboard — ดูคุณภาพ/ความพึงพอใจ", "—"],
  ["ผู้บริหาร", "/exec — KPI และ Pipeline สถานะจริง", "กดการ์ด Pipeline เพื่อเข้าสู่หน้าของฝ่ายที่ต้องทำ", "—"],
] as const;

function Card({ children }: { children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6">{children}</section>; }

export default function DocsPage() {
  return <main className="mx-auto max-w-6xl space-y-5 pb-10">
    <header className="rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-blue-900 px-6 py-8 text-white sm:px-9 sm:py-10"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-200">MPD FloorNow · SOP การทำงาน</p><h1 className="mt-2 text-2xl font-bold sm:text-4xl">ใครต้องทำอะไร ที่หน้าไหน และส่งต่องานอย่างไร</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300 sm:text-base">คู่มือสำหรับงานขายตรงและ BBPS ที่เข้าสู่ FloorNow ทุกฝ่ายใช้ใบสั่งงานกลางและเห็นข้อมูลชุดเดียวกัน</p></header>

    <Card><h2 className="text-lg font-bold text-slate-950">ภาพรวมงานหนึ่งใบ</h2><p className="mt-1 text-sm text-slate-500">เมื่อทำขั้นของตนเสร็จ ให้ตรวจผลลัพธ์ก่อนส่งต่อ</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{FLOW.map((item, index) => <Link key={item.owner} href={item.href} className="rounded-xl border border-slate-200 bg-slate-50 p-4 transition hover:border-blue-300 hover:bg-blue-50"><div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-blue-600 text-sm font-bold text-white">{index + 1}</span><b className="text-sm text-slate-900">{item.owner}</b></div><p className="mt-3 text-xs leading-5 text-slate-600">{item.action}</p><p className="mt-3 border-t border-slate-200 pt-2 text-xs font-semibold text-emerald-700">→ {item.status}</p></Link>)}</div></Card>

    <Card><h2 className="text-lg font-bold text-slate-950">Flow การส่งต่องาน</h2><p className="mt-1 text-sm text-slate-500">เริ่มจากข้อมูลขาย → ใบสั่งงานกลาง → หลักฐานหน้างาน → ผลประเมิน โดยไม่สร้างตั๋วซ้ำ</p><div className="mt-5 overflow-x-auto"><div className="flex min-w-[950px] items-stretch gap-2">{FLOW.map((item, index) => <div key={item.owner} className="flex items-center gap-2"><Link href={item.href} className="w-40 rounded-xl border border-blue-200 bg-blue-50 p-3 transition hover:bg-blue-100"><div className="text-[11px] font-bold text-blue-700">ขั้น {index + 1} · {item.owner}</div><div className="mt-2 text-xs leading-5 text-slate-700">{item.action}</div><div className="mt-3 rounded-md bg-white px-2 py-1 text-[11px] font-semibold text-emerald-700">ผลลัพธ์: {item.status}</div><div className="mt-2 text-[10px] text-blue-700 underline">เปิด {item.href}</div></Link>{index < FLOW.length - 1 ? <span className="text-xl font-bold text-slate-300">→</span> : null}</div>)}</div></div></Card>

    <Card><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-lg font-bold text-slate-950">RCAI: ใครทำ ใครรับผิดชอบ และใครต้องรับรู้</h2><p className="mt-1 text-sm text-slate-500"><b>R</b> ผู้ลงมือทำ · <b>C</b> ผู้ให้ข้อมูล/คำปรึกษา · <b>A</b> ผู้รับผิดชอบผลลัพธ์ · <b>I</b> ผู้ต้องรับทราบ</p></div><span className="text-xs text-slate-400">1 ขั้นมี A เดียว เพื่อไม่ให้เจ้าของงานซ้ำซ้อน</span></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="px-4 py-3">กิจกรรม</th><th className="px-4 py-3">R · Responsible</th><th className="px-4 py-3">C · Consulted</th><th className="px-4 py-3">A · Accountable</th><th className="px-4 py-3">I · Informed</th></tr></thead><tbody className="divide-y divide-slate-100">{RCAI.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={cell} className={`px-4 py-3 ${index === 0 ? "font-semibold text-slate-900" : index === 3 ? "font-semibold text-blue-700" : "text-slate-600"}`}>{cell}</td>)}</tr>)}</tbody></table></div></Card>

    <Card><h2 className="text-lg font-bold text-slate-950">แผนที่หน้าจอ: แต่ละแผนกต้องเข้าไปดูหน้าใด</h2><p className="mt-1 text-sm text-slate-500">ใช้หน้านี้เป็นจุดเริ่มต้นของการอบรมพนักงานใหม่</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[800px] text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="px-4 py-3">แผนก</th><th className="px-4 py-3">หน้าหลักที่ต้องใช้</th><th className="px-4 py-3">หน้ารอง/ใช้ติดตาม</th><th className="px-4 py-3">เพิ่มเติม</th></tr></thead><tbody className="divide-y divide-slate-100">{PAGE_MAP.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={cell} className={`px-4 py-3 ${index === 0 ? "font-semibold text-slate-900" : "text-slate-600"}`}>{cell}</td>)}</tr>)}</tbody></table></div></Card>

    <Card><h2 className="text-lg font-bold text-slate-950">กติกากลาง</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-blue-50 p-4 text-sm text-blue-950"><b>ใช้ใบสั่งงานเดียว</b><p className="mt-1 text-blue-800">ข้อมูลเปลี่ยนให้แก้และบันทึกในงานเดิม เพื่อเก็บประวัติและรูปไว้ครบ</p></div><div className="rounded-xl bg-amber-50 p-4 text-sm text-amber-950"><b>ส่งกลับต้องมีเหตุผล</b><p className="mt-1 text-amber-800">ระบุข้อมูลที่ขาดให้ผู้ส่งแก้ได้ทันที</p></div><div className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-950"><b>ส่งต่อเมื่อหลักฐานครบ</b><p className="mt-1 text-emerald-800">คลัง: จำนวนจริง+รูป · ช่าง: รูป+เศษ+ลายเซ็น · CS: คะแนน+ผลโทร</p></div></div></Card>

    <div className="grid gap-5 lg:grid-cols-2">{DEPARTMENTS.map((department) => <Card key={department.title}><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-bold text-slate-950">{department.icon} {department.title}</h2><p className="mt-1 text-sm text-slate-500">เป้าหมาย: {department.goal}</p></div><Link href={department.href} className="shrink-0 rounded-lg border border-blue-200 px-3 py-2 text-xs font-semibold text-blue-700 hover:bg-blue-50">{department.label}</Link></div><h3 className="mt-5 text-sm font-bold text-slate-800">ทำตามนี้</h3><ol className="mt-2 space-y-2">{department.steps.map((step, index) => <li key={step} className="flex gap-3 text-sm leading-6 text-slate-700"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-slate-100 text-xs font-bold text-slate-600">{index + 1}</span><span>{step}</span></li>)}</ol><div className="mt-4 rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-900"><b>ส่งต่อเมื่อ:</b> {department.result}</div><div className="mt-3 rounded-xl bg-amber-50 px-4 py-3 text-sm text-amber-900"><b>กรณีพิเศษ:</b> {department.exception}</div></Card>)}</div>

    <Card><h2 className="text-lg font-bold text-slate-950">เห็นสถานะแล้วต้องไปทำอะไร</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="px-4 py-3">สถานะ</th><th className="px-4 py-3">ผู้ส่งต่อ</th><th className="px-4 py-3">เจ้าของขั้นถัดไป</th><th className="px-4 py-3">หน้าที่ต้องเปิด</th></tr></thead><tbody className="divide-y divide-slate-100">{STATUS.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={cell} className={`px-4 py-3 ${index === 0 ? "font-semibold text-slate-900" : index === 2 ? "text-blue-700" : "text-slate-600"}`}>{cell}</td>)}</tr>)}</tbody></table></div></Card>

    <Card><h2 className="text-lg font-bold text-slate-950">คำถามที่พบบ่อย</h2><div className="mt-4 grid gap-3 md:grid-cols-2"><details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer font-semibold text-slate-800">งาน BBPS ถูกส่งกลับ แก้ที่ไหน?</summary><p className="mt-2 text-sm leading-6 text-slate-600">แก้ใน BBPS CRM ซึ่งเป็นข้อมูลต้นทาง แล้วรอ Sync กลับ FloorNow</p></details><details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer font-semibold text-slate-800">ฝ่ายขายดูสถานะช่างได้อย่างไร?</summary><p className="mt-2 text-sm leading-6 text-slate-600">เปิดงานจากจองคิวหรือใบสั่งงาน จะเห็นสถานะและรูปอัปเดตของทีมช่าง</p></details><details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer font-semibold text-slate-800">คลังหยิบของไม่เท่าตามแผน?</summary><p className="mt-2 text-sm leading-6 text-slate-600">บันทึกจำนวนจริงและรูปในขั้นเตรียมสินค้า เพื่อให้ช่างเห็นก่อนออกหน้างาน</p></details><details className="rounded-xl border border-slate-200 p-4"><summary className="cursor-pointer font-semibold text-slate-800">ผู้บริหารดูอะไร?</summary><p className="mt-2 text-sm leading-6 text-slate-600">เปิดภาพรวมผู้บริหาร แล้วกดสถานะใน Pipeline เพื่อไปยังฝ่ายที่ต้องจัดการ</p></details></div></Card>
  </main>;
}
