-- FloorNow P2.5: NCR control, CSAT SLA, closing guard and document outbox hooks.
-- Approved business rules: auto-approve phase 1; exception approver Supakrit.k@mpdgroup.co.

begin;

alter table public.floor_job_documents drop constraint if exists floor_job_documents_approval_complete;
alter table public.floor_job_documents add constraint floor_job_documents_approval_complete check (
  status <> 'approved' or (
    approved_at is not null and effective_from is not null and
    (approved_by is not null or is_system_generated)
  )
);

alter table public.ncr_reports
  add column if not exists severity text not null default 'medium',
  add column if not exists due_at timestamptz,
  add column if not exists owner_staff_id uuid references public.floor_staff_profiles(id) on delete set null,
  add column if not exists verified_at timestamptz,
  add column if not exists verified_by uuid references public.floor_staff_profiles(id) on delete set null;

do $$ begin
  alter table public.ncr_reports add constraint ncr_reports_severity_check
    check (severity in ('critical','high','medium','low'));
exception when duplicate_object then null; end $$;

alter table public.ncr_reports drop constraint if exists ncr_reports_status_check;
alter table public.ncr_reports add constraint ncr_reports_status_check
  check (status in ('open','investigating','corrective_action','verified','closed'));

update public.ncr_reports set due_at = coalesce(due_at, created_at + case severity
  when 'critical' then interval '4 hours' when 'high' then interval '24 hours'
  when 'medium' then interval '7 days' else interval '14 days' end);
update public.ncr_reports set status='corrective_action',updated_at=now() where status='approved';

create table if not exists public.floor_ncr_events (
  id bigint generated by default as identity primary key,
  ncr_id uuid not null references public.ncr_reports(id) on delete cascade,
  event_type text not null,
  from_status text,
  to_status text,
  actor_id uuid references public.floor_staff_profiles(id) on delete set null,
  detail jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);
create index if not exists floor_ncr_events_ncr_time_idx on public.floor_ncr_events(ncr_id, occurred_at desc);
alter table public.floor_ncr_events enable row level security;
revoke all on public.floor_ncr_events from anon, authenticated;
grant select on public.floor_ncr_events to authenticated;
drop policy if exists floor_ncr_events_active_staff_read on public.floor_ncr_events;
create policy floor_ncr_events_active_staff_read on public.floor_ncr_events for select to authenticated
  using ((select public.is_floor_staff_active()));

create table if not exists public.floor_csat_followups (
  job_no text primary key references public.install_jobs(job_no) on delete cascade,
  work_order_id uuid not null references public.floor_work_orders(id) on delete cascade,
  customer_signed_at timestamptz not null,
  due_at timestamptz not null,
  completed_at timestamptz,
  evaluation_id uuid references public.job_evaluations(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists floor_csat_followups_due_idx on public.floor_csat_followups(due_at) where completed_at is null;
alter table public.floor_csat_followups enable row level security;
revoke all on public.floor_csat_followups from anon, authenticated;
grant select on public.floor_csat_followups to authenticated;
drop policy if exists floor_csat_followups_active_staff_read on public.floor_csat_followups;
create policy floor_csat_followups_active_staff_read on public.floor_csat_followups for select to authenticated
  using ((select public.is_floor_staff_active()));

create table if not exists public.floor_close_exceptions (
  id uuid primary key default gen_random_uuid(),
  job_no text not null references public.install_jobs(job_no) on delete cascade,
  reason text not null check (char_length(btrim(reason)) between 5 and 1000),
  missing_requirements jsonb not null default '[]'::jsonb,
  approved_by uuid not null references public.floor_staff_profiles(id) on delete restrict,
  approved_at timestamptz not null default now(),
  used_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists floor_close_exceptions_job_idx on public.floor_close_exceptions(job_no, approved_at desc);
alter table public.floor_close_exceptions enable row level security;
revoke all on public.floor_close_exceptions from anon, authenticated;
grant select on public.floor_close_exceptions to authenticated;
drop policy if exists floor_close_exceptions_active_staff_read on public.floor_close_exceptions;
create policy floor_close_exceptions_active_staff_read on public.floor_close_exceptions for select to authenticated
  using ((select public.is_floor_staff_active()));

create or replace function public.create_floor_ncr(
  p_job_no text, p_title text, p_type text, p_product_sku text default null,
  p_quantity numeric default null, p_description text default null,
  p_estimated_value_thb numeric default null, p_created_by text default null,
  p_severity text default 'medium'
) returns uuid language plpgsql security definer set search_path=public as $$
declare v_actor public.floor_staff_profiles%rowtype; v_id uuid; v_due timestamptz;
begin
  select * into v_actor from public.floor_staff_profiles where id=(select auth.uid()) and is_active
    and role in ('admin','head_technician','warehouse','cs');
  if v_actor.id is null then raise exception 'NCR permission required'; end if;
  if nullif(btrim(coalesce(p_job_no,'')),'') is null or not exists(select 1 from public.install_jobs where job_no=p_job_no) then raise exception 'valid job number is required'; end if;
  if nullif(btrim(coalesce(p_title,'')),'') is null then raise exception 'NCR title is required'; end if;
  if p_severity not in ('critical','high','medium','low') then raise exception 'invalid NCR severity'; end if;
  v_due := now() + case p_severity when 'critical' then interval '4 hours' when 'high' then interval '24 hours' when 'medium' then interval '7 days' else interval '14 days' end;
  insert into public.ncr_reports(job_no,title,type,status,product_sku,quantity,description,estimated_value_thb,created_by,severity,due_at,owner_staff_id,created_at,updated_at)
  values(p_job_no,left(btrim(p_title),300),p_type,'open',nullif(btrim(coalesce(p_product_sku,'')),''),p_quantity,nullif(left(btrim(coalesce(p_description,'')),3000),''),p_estimated_value_thb,coalesce(nullif(btrim(coalesce(p_created_by,'')),''),v_actor.full_name),p_severity,v_due,v_actor.id,now(),now()) returning id into v_id;
  insert into public.floor_ncr_events(ncr_id,event_type,to_status,actor_id,detail) values(v_id,'created','open',v_actor.id,jsonb_build_object('severity',p_severity,'dueAt',v_due));
  return v_id;
end $$;
revoke all on function public.create_floor_ncr(text,text,text,text,numeric,text,numeric,text,text) from public,anon,authenticated;
grant execute on function public.create_floor_ncr(text,text,text,text,numeric,text,numeric,text,text) to authenticated;

create or replace function public.advance_floor_ncr(p_ncr_id uuid, p_next_status text)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_actor public.floor_staff_profiles%rowtype; v_ncr public.ncr_reports%rowtype; v_allowed boolean;
begin
  select * into v_actor from public.floor_staff_profiles where id=(select auth.uid()) and is_active
    and role in ('admin','head_technician','warehouse','cs');
  if v_actor.id is null then raise exception 'NCR permission required'; end if;
  select * into v_ncr from public.ncr_reports where id=p_ncr_id for update;
  if v_ncr.id is null then raise exception 'NCR not found'; end if;
  v_allowed := (v_ncr.status='open' and p_next_status='investigating') or
    (v_ncr.status='investigating' and p_next_status='corrective_action') or
    (v_ncr.status='corrective_action' and p_next_status='verified') or
    (v_ncr.status='verified' and p_next_status='closed');
  if not v_allowed then raise exception 'invalid NCR status transition'; end if;
  update public.ncr_reports set status=p_next_status,updated_at=now(),
    verified_at=case when p_next_status='verified' then now() else verified_at end,
    verified_by=case when p_next_status='verified' then v_actor.id else verified_by end,
    closed_at=case when p_next_status='closed' then now() else closed_at end where id=p_ncr_id;
  insert into public.floor_ncr_events(ncr_id,event_type,from_status,to_status,actor_id) values(p_ncr_id,'status_changed',v_ncr.status,p_next_status,v_actor.id);
  return true;
end $$;
revoke all on function public.advance_floor_ncr(uuid,text) from public,anon,authenticated;
grant execute on function public.advance_floor_ncr(uuid,text) to authenticated;

create or replace function public.approve_floor_close_exception(p_job_no text,p_reason text)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_actor public.floor_staff_profiles%rowtype; v_id uuid; v_missing jsonb;
begin
  select * into v_actor from public.floor_staff_profiles where id=(select auth.uid()) and is_active
    and lower(email)=lower('Supakrit.k@mpdgroup.co');
  if v_actor.id is null then raise exception 'close exception approver permission required'; end if;
  select to_jsonb(array_remove(array[
    case when not exists(select 1 from public.floor_work_order_events e join public.floor_work_orders w on w.id=e.work_order_id where w.job_no=p_job_no and e.event_type='customer_signed') then 'customer_signature' end,
    case when not exists(select 1 from public.floor_remnant_reports r where r.job_no=p_job_no and r.status='accepted') then 'accepted_remnant_report' end,
    case when not exists(select 1 from public.job_evaluations j where j.job_no=p_job_no and j.satisfaction_score is not null) then 'csat' end
  ]::text[],null)) into v_missing;
  insert into public.floor_close_exceptions(job_no,reason,missing_requirements,approved_by) values(p_job_no,btrim(p_reason),v_missing,v_actor.id) returning id into v_id;
  return v_id;
end $$;
revoke all on function public.approve_floor_close_exception(text,text) from public,anon,authenticated;
grant execute on function public.approve_floor_close_exception(text,text) to authenticated;

-- Track CSAT due three days after customer signature without blocking signature flow.
create or replace function public.track_floor_csat_and_closing_documents()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_job_no text;
begin
  select job_no into v_job_no from public.floor_work_orders where id=new.work_order_id;
  if v_job_no is null then return new; end if;
  begin
    if new.event_type='customer_signed' then
      insert into public.floor_csat_followups(job_no,work_order_id,customer_signed_at,due_at)
      values(v_job_no,new.work_order_id,new.occurred_at,new.occurred_at+interval '3 days')
      on conflict(job_no) do update set work_order_id=excluded.work_order_id,customer_signed_at=excluded.customer_signed_at,due_at=excluded.due_at,completed_at=null,evaluation_id=null,updated_at=now();
      perform public.enqueue_floor_document_job(v_job_no,'customer_acceptance','04-installation','quality_record','customer_signed',new.id::text,new.occurred_at);
    elsif new.event_type='remnants_submitted' then
      perform public.enqueue_floor_document_job(v_job_no,'remnant_report','04-installation','quality_record','remnants_submitted',new.id::text,new.occurred_at);
    elsif new.event_type='cs_closed' then
      perform public.enqueue_floor_document_job(v_job_no,'handover','05-closing','quality_record','cs_closed',new.id::text,new.occurred_at);
    end if;
  exception when others then raise warning 'Closing document enqueue skipped for event %: %',new.id,sqlerrm; end;
  return new;
end $$;
revoke all on function public.track_floor_csat_and_closing_documents() from public,anon,authenticated;
drop trigger if exists trg_floor_docgen_closing_events on public.floor_work_order_events;
create trigger trg_floor_docgen_closing_events after insert on public.floor_work_order_events for each row execute function public.track_floor_csat_and_closing_documents();

create or replace function public.enqueue_floor_csat_document()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_source timestamptz:=coalesce(new.updated_at,new.created_at,now());
begin
  if new.satisfaction_score is null then return new; end if;
  update public.floor_csat_followups set completed_at=now(),evaluation_id=new.id,updated_at=now() where job_no=new.job_no;
  perform public.enqueue_floor_document_job(new.job_no,'csat','05-closing','quality_record','csat_completed',new.id::text,v_source);
  return new;
exception when others then raise warning 'CSAT document enqueue skipped for evaluation %: %',new.id,sqlerrm; return new;
end $$;
revoke all on function public.enqueue_floor_csat_document() from public,anon,authenticated;
drop trigger if exists trg_floor_docgen_csat on public.job_evaluations;
create trigger trg_floor_docgen_csat after insert or update of satisfaction_score,answers,issues_text,needs_followup on public.job_evaluations for each row execute function public.enqueue_floor_csat_document();

create or replace function public.enqueue_floor_ncr_document()
returns trigger language plpgsql security definer set search_path=public as $$
declare v_source timestamptz:=coalesce(new.updated_at,new.created_at,now());
begin
  if new.job_no is null then return new; end if;
  perform public.enqueue_floor_document_job(new.job_no,'ncr','05-closing','controlled_document','ncr_'||new.status,new.id::text,v_source);
  return new;
exception when others then raise warning 'NCR document enqueue skipped for NCR %: %',new.id,sqlerrm; return new;
end $$;
revoke all on function public.enqueue_floor_ncr_document() from public,anon,authenticated;
drop trigger if exists trg_floor_docgen_ncr on public.ncr_reports;
create trigger trg_floor_docgen_ncr after insert or update of title,type,status,severity,due_at,description on public.ncr_reports for each row execute function public.enqueue_floor_ncr_document();

-- Preserve the existing RPC name consumed by the UI, with evidence/NCR guard and audited exception.
create or replace function public.close_floor_work_order_cs_v3(p_work_order_id uuid)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_order public.floor_work_orders%rowtype; v_actor public.floor_staff_profiles%rowtype; v_exception public.floor_close_exceptions%rowtype; v_missing text[]:=array[]::text[];
begin
  select * into v_actor from public.floor_staff_profiles where id=(select auth.uid()) and is_active and role in ('admin','cs');
  if v_actor.id is null then raise exception 'CS permission required'; end if;
  select * into v_order from public.floor_work_orders where id=p_work_order_id and status='waiting_cs' for update;
  if v_order.id is null then raise exception 'work order is not waiting for CS'; end if;
  if not exists(select 1 from public.floor_work_order_events where work_order_id=v_order.id and event_type='customer_signed') then v_missing:=array_append(v_missing,'customer_signature'); end if;
  if not exists(select 1 from public.floor_remnant_reports where job_no=v_order.job_no and status='accepted') then v_missing:=array_append(v_missing,'accepted_remnant_report'); end if;
  if not exists(select 1 from public.job_evaluations where job_no=v_order.job_no and satisfaction_score is not null) then v_missing:=array_append(v_missing,'csat'); end if;
  if exists(select 1 from public.ncr_reports where job_no=v_order.job_no and severity in ('critical','high') and status<>'closed') then v_missing:=array_append(v_missing,'open_high_ncr'); end if;
  if cardinality(v_missing)>0 then
    select * into v_exception from public.floor_close_exceptions where job_no=v_order.job_no and used_at is null order by approved_at desc limit 1 for update;
    if v_exception.id is null then raise exception 'closing requirements incomplete: %',array_to_string(v_missing,', '); end if;
    update public.floor_close_exceptions set used_at=now(),missing_requirements=to_jsonb(v_missing) where id=v_exception.id;
  end if;
  update public.floor_work_orders set status='closed',closed_at=now(),updated_at=now() where id=v_order.id;
  update public.install_jobs set stage=6,status='เสร็จสิ้น',waiting_on='ไม่ได้ค้าง',waiting_since=null,closed_at=coalesce(closed_at,now()),updated_at=now() where job_no=v_order.job_no;
  insert into public.floor_work_order_events(work_order_id,event_type,from_status,to_status,actor_staff_id,actor_name,note,metadata)
  values(v_order.id,'cs_closed','waiting_cs','closed',v_actor.id,v_actor.full_name,'CS ประเมินและปิดงาน',jsonb_build_object('exceptionId',v_exception.id,'missing',v_missing));
  return true;
end $$;
revoke all on function public.close_floor_work_order_cs_v3(uuid) from public,anon,authenticated;
grant execute on function public.close_floor_work_order_cs_v3(uuid) to authenticated;

-- All NCR mutations now pass through audited SECURITY DEFINER RPCs.
revoke insert,update,delete on public.ncr_reports from authenticated;

commit;
