-- Personal technician workspace, per-appointment assignments, and audit evidence.

create table if not exists public.floor_technicians (
  id uuid primary key default gen_random_uuid(),
  team_id uuid references public.tech_teams(id) on delete set null,
  name text not null,
  phone text,
  is_team_lead boolean not null default false,
  is_active boolean not null default true,
  personal_token uuid not null default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint floor_technicians_name_not_blank check (btrim(name) <> ''),
  constraint floor_technicians_personal_token_key unique (personal_token)
);

create index if not exists floor_technicians_team_active_idx
  on public.floor_technicians(team_id, is_active, name);

create table if not exists public.appointment_technicians (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null references public.appointments(id) on delete restrict,
  technician_id uuid not null references public.floor_technicians(id) on delete restrict,
  is_lead boolean not null default false,
  is_active boolean not null default true,
  assigned_by text not null default 'หัวหน้าช่าง',
  assigned_at timestamptz not null default now(),
  revoked_at timestamptz,
  first_opened_at timestamptz,
  last_opened_at timestamptz,
  open_count integer not null default 0,
  acknowledged_at timestamptz,
  constraint appointment_technicians_open_count_nonnegative check (open_count >= 0),
  constraint appointment_technicians_unique unique (appointment_id, technician_id)
);

create index if not exists appointment_technicians_technician_active_idx
  on public.appointment_technicians(technician_id, is_active, appointment_id);

create index if not exists appointment_technicians_appointment_active_idx
  on public.appointment_technicians(appointment_id, is_active);

create table if not exists public.technician_work_events (
  id bigint generated by default as identity primary key,
  assignment_id uuid not null references public.appointment_technicians(id) on delete restrict,
  event_type text not null,
  occurred_at timestamptz not null default now(),
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  constraint technician_work_events_type_check
    check (event_type in ('assigned', 'revoked', 'opened', 'acknowledged'))
);

create index if not exists technician_work_events_assignment_time_idx
  on public.technician_work_events(assignment_id, occurred_at desc);

alter table public.floor_technicians enable row level security;
alter table public.appointment_technicians enable row level security;
alter table public.technician_work_events enable row level security;

drop policy if exists floor_technicians_anon_select on public.floor_technicians;
create policy floor_technicians_anon_select on public.floor_technicians
  for select to anon using (true);
drop policy if exists floor_technicians_anon_insert on public.floor_technicians;
create policy floor_technicians_anon_insert on public.floor_technicians
  for insert to anon with check (true);
drop policy if exists floor_technicians_anon_update on public.floor_technicians;
create policy floor_technicians_anon_update on public.floor_technicians
  for update to anon using (true) with check (true);
drop policy if exists floor_technicians_auth_all on public.floor_technicians;
create policy floor_technicians_auth_all on public.floor_technicians
  for all to authenticated using (true) with check (true);

drop policy if exists appointment_technicians_anon_select on public.appointment_technicians;
create policy appointment_technicians_anon_select on public.appointment_technicians
  for select to anon using (true);
drop policy if exists appointment_technicians_anon_insert on public.appointment_technicians;
create policy appointment_technicians_anon_insert on public.appointment_technicians
  for insert to anon with check (true);
drop policy if exists appointment_technicians_anon_update on public.appointment_technicians;
create policy appointment_technicians_anon_update on public.appointment_technicians
  for update to anon using (true) with check (true);
drop policy if exists appointment_technicians_auth_all on public.appointment_technicians;
create policy appointment_technicians_auth_all on public.appointment_technicians
  for all to authenticated using (true) with check (true);

drop policy if exists technician_work_events_auth_all on public.technician_work_events;
create policy technician_work_events_auth_all on public.technician_work_events
  for all to authenticated using (true) with check (true);

revoke all on public.floor_technicians from anon;
grant select (id, team_id, name, phone, is_team_lead, is_active, created_at, updated_at)
  on public.floor_technicians to anon;
grant insert (id, team_id, name, phone, is_team_lead, is_active, personal_token, created_at, updated_at)
  on public.floor_technicians to anon;
grant update (team_id, name, phone, is_team_lead, is_active, personal_token, updated_at)
  on public.floor_technicians to anon;

revoke all on public.appointment_technicians from anon;
grant select, insert, update on public.appointment_technicians to anon;

revoke all on public.technician_work_events from anon;
revoke all on sequence public.technician_work_events_id_seq from anon;

grant select, insert, update, delete on public.floor_technicians to authenticated;
grant select, insert, update, delete on public.appointment_technicians to authenticated;
grant select, insert, update, delete on public.technician_work_events to authenticated;
grant usage, select on sequence public.technician_work_events_id_seq to authenticated;

create or replace function public.get_technician_workspace(p_token uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'technician', jsonb_build_object(
      'id', t.id,
      'name', t.name,
      'phone', t.phone,
      'teamId', t.team_id,
      'teamName', team.name,
      'isTeamLead', t.is_team_lead
    ),
    'assignments', coalesce((
      select jsonb_agg(jsonb_build_object(
        'assignmentId', a.id,
        'isLead', a.is_lead,
        'firstOpenedAt', a.first_opened_at,
        'lastOpenedAt', a.last_opened_at,
        'openCount', a.open_count,
        'acknowledgedAt', a.acknowledged_at,
        'appointmentId', ap.id,
        'slotStart', ap.slot_start,
        'slotEnd', ap.slot_end,
        'appointmentStatus', ap.status,
        'teamName', ap_team.name,
        'notes', ap.notes,
        'requirement', ap.requirement,
        'jobNo', j.job_no,
        'source', j.source,
        'billNo', j.bill_no,
        'customerName', j.customer_name,
        'customerPhone', j.customer_phone,
        'address', j.address,
        'locationUrl', j.location_url,
        'productName', j.product_name,
        'surveyData', j.survey_data
      ) order by ap.slot_start)
      from public.appointment_technicians a
      join public.appointments ap on ap.id = a.appointment_id
      left join public.tech_teams ap_team on ap_team.id = ap.tech_id
      left join public.install_jobs j on j.job_no = ap.job_id
      where a.technician_id = t.id
        and a.is_active = true
        and ap.status <> 'cancelled'
    ), '[]'::jsonb)
  )
  from public.floor_technicians t
  left join public.tech_teams team on team.id = t.team_id
  where t.personal_token = p_token
    and t.is_active = true;
$$;

revoke all on function public.get_technician_workspace(uuid) from public;
grant execute on function public.get_technician_workspace(uuid) to anon, authenticated;

create or replace function public.record_technician_work_event(
  p_token uuid,
  p_assignment_id uuid,
  p_event_type text,
  p_user_agent text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_assignment_id uuid;
begin
  if p_event_type not in ('opened', 'acknowledged') then
    return false;
  end if;

  select a.id into v_assignment_id
  from public.appointment_technicians a
  join public.floor_technicians t on t.id = a.technician_id
  where a.id = p_assignment_id
    and a.is_active = true
    and t.is_active = true
    and t.personal_token = p_token;

  if v_assignment_id is null then
    return false;
  end if;

  if p_event_type = 'opened' then
    update public.appointment_technicians
    set first_opened_at = coalesce(first_opened_at, now()),
        last_opened_at = now(),
        open_count = open_count + 1
    where id = v_assignment_id;
  else
    update public.appointment_technicians
    set acknowledged_at = coalesce(acknowledged_at, now())
    where id = v_assignment_id;
  end if;

  insert into public.technician_work_events(assignment_id, event_type, user_agent)
  values (v_assignment_id, p_event_type, nullif(left(p_user_agent, 500), ''));

  return true;
end;
$$;

revoke all on function public.record_technician_work_event(uuid, uuid, text, text) from public;
grant execute on function public.record_technician_work_event(uuid, uuid, text, text) to anon, authenticated;

comment on table public.floor_technicians is
  'Floor-owned technician directory. personal_token is a capability link for each technician workspace.';
comment on table public.appointment_technicians is
  'Per-appointment individual technician assignments and open/acknowledgement evidence.';
comment on table public.technician_work_events is
  'Append-only evidence for assignment, revocation, work-detail opens, and acknowledgements.';
