-- FloorNow Operational Flow V2
-- Central work order shared by sales, head technicians, warehouse, field crews and CS.

create table if not exists public.floor_work_orders (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null references public.appointments(id) on delete restrict,
  job_no text not null,
  status text not null default 'head_review',
  revision integer not null default 1,
  confirmed_by uuid references public.floor_staff_profiles(id) on delete set null,
  confirmed_at timestamptz,
  warehouse_assignee_id uuid references public.floor_staff_profiles(id) on delete set null,
  warehouse_accepted_at timestamptz,
  warehouse_completed_at timestamptz,
  installation_lead_assignment_id uuid references public.appointment_technicians(id) on delete set null,
  installation_accepted_at timestamptz,
  waiting_cs_at timestamptz,
  closed_at timestamptz,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint floor_work_orders_appointment_unique unique (appointment_id),
  constraint floor_work_orders_status_check check (status in (
    'head_review', 'returned_sales', 'warehouse_waiting', 'warehouse_preparing',
    'ready_to_install', 'installing', 'waiting_cs', 'closed', 'cancelled'
  ))
);

create index if not exists floor_work_orders_status_time_idx
  on public.floor_work_orders(status, updated_at desc);
create index if not exists floor_work_orders_job_idx
  on public.floor_work_orders(job_no, created_at desc);

create table if not exists public.floor_work_order_items (
  id uuid primary key default gen_random_uuid(),
  work_order_id uuid not null references public.floor_work_orders(id) on delete cascade,
  category text not null,
  item_name text not null,
  sku text,
  specification text,
  planned_qty numeric(12,2) not null,
  actual_qty numeric(12,2),
  unit text not null,
  source_type text not null default 'new',
  note text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint floor_work_order_items_category_check check (category in ('floor_material','remnant','accessory','consumable','equipment','tool')),
  constraint floor_work_order_items_source_check check (source_type in ('new','remnant','warehouse','bring_along','other')),
  constraint floor_work_order_items_qty_check check (planned_qty >= 0 and (actual_qty is null or actual_qty >= 0))
);

create index if not exists floor_work_order_items_order_idx
  on public.floor_work_order_items(work_order_id, sort_order, created_at);

create table if not exists public.floor_work_order_events (
  id bigint generated by default as identity primary key,
  work_order_id uuid not null references public.floor_work_orders(id) on delete cascade,
  event_type text not null,
  from_status text,
  to_status text,
  actor_staff_id uuid references public.floor_staff_profiles(id) on delete set null,
  actor_technician_id uuid references public.floor_technicians(id) on delete set null,
  actor_name text not null,
  note text,
  photo_paths text[] not null default '{}',
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

create index if not exists floor_work_order_events_order_time_idx
  on public.floor_work_order_events(work_order_id, occurred_at desc);

alter table public.floor_work_orders enable row level security;
alter table public.floor_work_order_items enable row level security;
alter table public.floor_work_order_events enable row level security;

revoke all on public.floor_work_orders from anon, authenticated;
revoke all on public.floor_work_order_items from anon, authenticated;
revoke all on public.floor_work_order_events from anon, authenticated;
revoke all on sequence public.floor_work_order_events_id_seq from anon, authenticated;
grant select on public.floor_work_orders, public.floor_work_order_items, public.floor_work_order_events to authenticated;

drop policy if exists floor_work_orders_staff_read on public.floor_work_orders;
create policy floor_work_orders_staff_read on public.floor_work_orders for select to authenticated
  using (exists (select 1 from public.floor_staff_profiles p where p.id = (select auth.uid()) and p.is_active));
drop policy if exists floor_work_order_items_staff_read on public.floor_work_order_items;
create policy floor_work_order_items_staff_read on public.floor_work_order_items for select to authenticated
  using (exists (select 1 from public.floor_staff_profiles p where p.id = (select auth.uid()) and p.is_active));
drop policy if exists floor_work_order_events_staff_read on public.floor_work_order_events;
create policy floor_work_order_events_staff_read on public.floor_work_order_events for select to authenticated
  using (exists (select 1 from public.floor_staff_profiles p where p.id = (select auth.uid()) and p.is_active));

create or replace function public.ensure_floor_work_order_for_appointment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.job_id is not null and new.status <> 'cancelled' then
    insert into public.floor_work_orders(appointment_id, job_no, status)
    values (new.id, new.job_id, case when new.status = 'completed' then 'waiting_cs' when new.status = 'confirmed' then 'ready_to_install' else 'head_review' end)
    on conflict (appointment_id) do update set job_no = excluded.job_no, updated_at = now();
  elsif new.status = 'cancelled' then
    update public.floor_work_orders set status = 'cancelled', updated_at = now() where appointment_id = new.id and status <> 'closed';
  end if;
  return new;
end;
$$;

drop trigger if exists ensure_floor_work_order_after_appointment on public.appointments;
create trigger ensure_floor_work_order_after_appointment
  after insert or update of job_id, status on public.appointments
  for each row execute function public.ensure_floor_work_order_for_appointment();

insert into public.floor_work_orders(appointment_id, job_no, status)
select ap.id, ap.job_id,
  case when ap.status = 'completed' then 'waiting_cs' when ap.status = 'confirmed' then 'ready_to_install' else 'head_review' end
from public.appointments ap
where ap.job_id is not null and ap.status <> 'cancelled'
on conflict (appointment_id) do nothing;

create or replace function public.confirm_floor_work_order_v2(
  p_work_order_id uuid,
  p_items jsonb,
  p_note text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.floor_work_orders%rowtype;
  v_appt public.appointments%rowtype;
  v_job public.install_jobs%rowtype;
  v_actor public.floor_staff_profiles%rowtype;
  v_item jsonb;
  v_sort integer := 0;
begin
  select * into v_actor from public.floor_staff_profiles where id = (select auth.uid()) and is_active and role in ('admin','head_technician');
  if v_actor.id is null then raise exception 'head technician permission required'; end if;
  select * into v_order from public.floor_work_orders where id = p_work_order_id and status in ('head_review','returned_sales') for update;
  if v_order.id is null then raise exception 'work order is not awaiting confirmation'; end if;
  select * into v_appt from public.appointments where id = v_order.appointment_id and status <> 'cancelled';
  select * into v_job from public.install_jobs where job_no = v_order.job_no;
  if v_appt.id is null or v_job.job_no is null then raise exception 'appointment or job not found'; end if;
  if nullif(btrim(coalesce(v_job.customer_name,'')),'') is null
     or nullif(btrim(coalesce(v_job.customer_phone,'')),'') is null
     or (nullif(btrim(coalesce(v_job.address,'')),'') is null and nullif(btrim(coalesce(v_job.location_url,'')),'') is null)
     or nullif(btrim(coalesce(v_job.product_name,v_appt.requirement,'')),'') is null then
    raise exception 'customer, phone, location and work specification are required';
  end if;
  if not exists (select 1 from public.appointment_technicians a where a.appointment_id = v_appt.id and a.is_active and a.is_lead) then
    raise exception 'lead technician assignment is required';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'at least one material or equipment item is required'; end if;

  delete from public.floor_work_order_items where work_order_id = v_order.id;
  for v_item in select * from jsonb_array_elements(p_items)
  loop
    if coalesce(v_item->>'category','') not in ('floor_material','remnant','accessory','consumable','equipment','tool')
       or nullif(btrim(coalesce(v_item->>'itemName','')),'') is null
       or nullif(btrim(coalesce(v_item->>'unit','')),'') is null
       or coalesce((v_item->>'plannedQty')::numeric,-1) < 0 then
      raise exception 'invalid work order item';
    end if;
    insert into public.floor_work_order_items(work_order_id,category,item_name,sku,specification,planned_qty,unit,source_type,note,sort_order)
    values (v_order.id,v_item->>'category',btrim(v_item->>'itemName'),nullif(btrim(coalesce(v_item->>'sku','')),''),nullif(btrim(coalesce(v_item->>'specification','')),''),(v_item->>'plannedQty')::numeric,btrim(v_item->>'unit'),coalesce(nullif(v_item->>'sourceType',''),'new'),nullif(btrim(coalesce(v_item->>'note','')),''),v_sort);
    v_sort := v_sort + 1;
  end loop;

  insert into public.floor_job_materials(appointment_id,planned_sheet_count,planned_by,planned_at,updated_at)
  select v_order.appointment_id,
    coalesce(ceil(sum(planned_qty) filter (where category in ('floor_material','remnant') and unit in ('แผ่น','sheet','sheets'))),0)::integer,
    v_actor.full_name,now(),now()
  from public.floor_work_order_items where work_order_id=v_order.id
  on conflict (appointment_id) do update set planned_sheet_count=excluded.planned_sheet_count,planned_by=excluded.planned_by,planned_at=excluded.planned_at,updated_at=excluded.updated_at;

  update public.floor_work_orders set status = 'warehouse_waiting', revision = revision + 1,
    confirmed_by = v_actor.id, confirmed_at = now(), note = nullif(btrim(coalesce(p_note,'')),''), updated_at = now()
  where id = v_order.id;
  update public.appointments set status = 'confirmed', confirmed_at = now() where id = v_order.appointment_id;
  update public.install_jobs set status = 'รอคลังรับงาน', waiting_on = 'คลังสินค้า', waiting_since = now(), flag_note = null, updated_at = now() where job_no = v_order.job_no;
  insert into public.floor_work_order_events(work_order_id,event_type,from_status,to_status,actor_staff_id,actor_name,note)
  values (v_order.id,'head_confirmed',v_order.status,'warehouse_waiting',v_actor.id,v_actor.full_name,nullif(btrim(coalesce(p_note,'')),''));
  return true;
end;
$$;

create or replace function public.accept_floor_warehouse_order_v2(p_work_order_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare v_order public.floor_work_orders%rowtype; v_actor public.floor_staff_profiles%rowtype;
begin
  select * into v_actor from public.floor_staff_profiles where id = (select auth.uid()) and is_active and role in ('admin','warehouse');
  if v_actor.id is null then raise exception 'warehouse permission required'; end if;
  select * into v_order from public.floor_work_orders where id = p_work_order_id and status = 'warehouse_waiting' for update;
  if v_order.id is null then raise exception 'work order is not waiting for warehouse'; end if;
  update public.floor_work_orders set status='warehouse_preparing',warehouse_assignee_id=v_actor.id,warehouse_accepted_at=now(),updated_at=now() where id=v_order.id;
  update public.install_jobs set status='กำลังเตรียมสินค้า',waiting_on=v_actor.full_name,waiting_since=now(),updated_at=now() where job_no=v_order.job_no;
  insert into public.floor_work_order_events(work_order_id,event_type,from_status,to_status,actor_staff_id,actor_name)
  values(v_order.id,'warehouse_accepted','warehouse_waiting','warehouse_preparing',v_actor.id,v_actor.full_name);
  return true;
end;
$$;

create or replace function public.complete_floor_warehouse_order_v2(
  p_work_order_id uuid,
  p_actual_items jsonb,
  p_photo_paths text[],
  p_note text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare v_order public.floor_work_orders%rowtype; v_actor public.floor_staff_profiles%rowtype; v_item jsonb;
begin
  select * into v_actor from public.floor_staff_profiles where id = (select auth.uid()) and is_active and role in ('admin','warehouse');
  if v_actor.id is null then raise exception 'warehouse permission required'; end if;
  select * into v_order from public.floor_work_orders where id=p_work_order_id and status='warehouse_preparing' for update;
  if v_order.id is null then raise exception 'work order is not being prepared'; end if;
  if v_order.warehouse_assignee_id <> v_actor.id and v_actor.role <> 'admin' then raise exception 'only the staff member who accepted this order can complete it'; end if;
  if coalesce(cardinality(p_photo_paths),0)=0 then raise exception 'warehouse evidence photo is required'; end if;
  if jsonb_typeof(p_actual_items) <> 'array' then raise exception 'actual quantities are required'; end if;
  for v_item in select * from jsonb_array_elements(p_actual_items)
  loop
    if coalesce((v_item->>'actualQty')::numeric,-1) < 0 then raise exception 'actual quantity is required for every item'; end if;
    update public.floor_work_order_items set actual_qty=(v_item->>'actualQty')::numeric,updated_at=now()
    where id=(v_item->>'id')::uuid and work_order_id=v_order.id;
  end loop;
  if exists(select 1 from public.floor_work_order_items where work_order_id=v_order.id and actual_qty is null) then raise exception 'actual quantity is required for every item'; end if;
  update public.floor_work_orders set status='ready_to_install',warehouse_completed_at=now(),updated_at=now() where id=v_order.id;
  update public.install_jobs set status='รอติดตั้ง',waiting_on='หัวหน้าทีมช่าง',waiting_since=now(),updated_at=now() where job_no=v_order.job_no;
  insert into public.floor_work_order_events(work_order_id,event_type,from_status,to_status,actor_staff_id,actor_name,note,photo_paths)
  values(v_order.id,'warehouse_completed','warehouse_preparing','ready_to_install',v_actor.id,v_actor.full_name,nullif(btrim(coalesce(p_note,'')),''),p_photo_paths);
  return true;
end;
$$;

create or replace function public.get_technician_work_order_v2(p_token uuid,p_pin text,p_assignment_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'id',wo.id,'status',wo.status,'revision',wo.revision,'note',wo.note,
    'warehouseAssignee',warehouse.full_name,'warehouseAcceptedAt',wo.warehouse_accepted_at,'warehouseCompletedAt',wo.warehouse_completed_at,
    'isLead',a.is_lead,
    'items',coalesce((select jsonb_agg(jsonb_build_object('id',i.id,'category',i.category,'itemName',i.item_name,'sku',i.sku,'specification',i.specification,'plannedQty',i.planned_qty,'actualQty',i.actual_qty,'unit',i.unit,'sourceType',i.source_type,'note',i.note) order by i.sort_order) from public.floor_work_order_items i where i.work_order_id=wo.id),'[]'::jsonb),
    'events',coalesce((select jsonb_agg(jsonb_build_object('id',e.id,'eventType',e.event_type,'fromStatus',e.from_status,'toStatus',e.to_status,'actorName',e.actor_name,'note',e.note,'photoPaths',e.photo_paths,'occurredAt',e.occurred_at) order by e.occurred_at) from public.floor_work_order_events e where e.work_order_id=wo.id),'[]'::jsonb)
  )
  from public.appointment_technicians a
  join public.floor_technicians t on t.id=a.technician_id
  join public.floor_work_orders wo on wo.appointment_id=a.appointment_id
  left join public.floor_staff_profiles warehouse on warehouse.id=wo.warehouse_assignee_id
  where a.id=p_assignment_id and a.is_active and t.is_active and t.personal_token=p_token and t.pin_hash is not null
    and extensions.crypt(regexp_replace(coalesce(p_pin,''),'\s+','','g'),t.pin_hash)=t.pin_hash;
$$;

create or replace function public.sync_floor_work_order_from_progress_v2()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare v_order public.floor_work_orders%rowtype; v_assignment public.appointment_technicians%rowtype; v_name text; v_slot_start timestamptz;
begin
  select * into v_order from public.floor_work_orders where appointment_id=new.appointment_id for update;
  if v_order.id is null then return new; end if;
  select * into v_assignment from public.appointment_technicians where id=new.assignment_id;
  select name into v_name from public.floor_technicians where id=new.technician_id;
  if new.status='travelling' and v_order.status='ready_to_install' then
    if not v_assignment.is_lead then raise exception 'lead technician must accept installation first'; end if;
    select slot_start into v_slot_start from public.appointments where id=v_order.appointment_id;
    if timezone('Asia/Bangkok',now())::date < timezone('Asia/Bangkok',v_slot_start)::date then raise exception 'installation can be accepted on the scheduled date'; end if;
    update public.floor_work_orders set status='installing',installation_lead_assignment_id=new.assignment_id,installation_accepted_at=now(),updated_at=now() where id=v_order.id;
    update public.install_jobs set status='กำลังติดตั้ง',waiting_on=v_name,waiting_since=now(),updated_at=now() where job_no=v_order.job_no;
    insert into public.floor_work_order_events(work_order_id,event_type,from_status,to_status,actor_technician_id,actor_name,note,photo_paths,metadata)
    values(v_order.id,'installation_accepted','ready_to_install','installing',new.technician_id,coalesce(v_name,'หัวหน้าทีมช่าง'),new.note,new.photo_paths,jsonb_build_object('pickedSheetCount',new.picked_sheet_count));
  elsif new.status in ('arrived','installing','completed') then
    insert into public.floor_work_order_events(work_order_id,event_type,from_status,to_status,actor_technician_id,actor_name,note,photo_paths)
    values(v_order.id,'field_'||new.status,v_order.status,v_order.status,new.technician_id,coalesce(v_name,'ช่าง'),new.note,new.photo_paths);
  elsif new.status='customer_signed' then
    if v_order.status <> 'installing' then raise exception 'installation is not active'; end if;
    update public.floor_work_orders set status='waiting_cs',waiting_cs_at=now(),updated_at=now() where id=v_order.id;
    update public.appointments set status='completed' where id=v_order.appointment_id;
    update public.install_jobs set stage=greatest(stage,5),status='รอ CS โทรประเมิน',waiting_on='CS',waiting_since=now(),updated_at=now() where job_no=v_order.job_no;
    insert into public.floor_work_order_events(work_order_id,event_type,from_status,to_status,actor_technician_id,actor_name,note,photo_paths,metadata)
    values(v_order.id,'customer_signed','installing','waiting_cs',new.technician_id,coalesce(v_name,'ช่าง'),new.note,new.photo_paths,jsonb_build_object('customerName',new.customer_signed_name,'signaturePath',new.customer_signature_path));
  end if;
  return new;
end;
$$;

drop trigger if exists sync_floor_work_order_after_progress_v2 on public.floor_work_progress_events;
create trigger sync_floor_work_order_after_progress_v2
  after insert on public.floor_work_progress_events
  for each row execute function public.sync_floor_work_order_from_progress_v2();

revoke all on function public.confirm_floor_work_order_v2(uuid,jsonb,text) from public,anon,authenticated;
revoke all on function public.accept_floor_warehouse_order_v2(uuid) from public,anon,authenticated;
revoke all on function public.complete_floor_warehouse_order_v2(uuid,jsonb,text[],text) from public,anon,authenticated;
revoke all on function public.get_technician_work_order_v2(uuid,text,uuid) from public,anon,authenticated;
grant execute on function public.confirm_floor_work_order_v2(uuid,jsonb,text) to authenticated;
grant execute on function public.accept_floor_warehouse_order_v2(uuid) to authenticated;
grant execute on function public.complete_floor_warehouse_order_v2(uuid,jsonb,text[],text) to authenticated;
grant execute on function public.get_technician_work_order_v2(uuid,text,uuid) to anon,authenticated;
