-- Employee authentication hardening and mobile notifications for FloorNow.
-- This migration only touches FloorNow-owned tables.

create or replace function public.is_floor_staff_active()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.floor_staff_profiles p
    where p.id = (select auth.uid()) and p.is_active
  );
$$;

create or replace function public.floor_staff_has_role(p_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.floor_staff_profiles p
    where p.id = (select auth.uid()) and p.is_active and p.role = any(p_roles)
  );
$$;

revoke all on function public.is_floor_staff_active() from public, anon, authenticated;
revoke all on function public.floor_staff_has_role(text[]) from public, anon, authenticated;
grant execute on function public.is_floor_staff_active() to authenticated;
grant execute on function public.floor_staff_has_role(text[]) to authenticated;

-- Legacy open-table policies are removed in the follow-up hardening migration
-- after the RPC-based technician workspace has reached production.

-- Notification inbox. One notification belongs to either an authenticated
-- office employee or a technician using the existing personal link + PIN.
create table if not exists public.floor_notifications (
  id bigint generated by default as identity primary key,
  recipient_user_id uuid references auth.users(id) on delete cascade,
  recipient_technician_id uuid references public.floor_technicians(id) on delete cascade,
  event_type text not null,
  title text not null,
  body text,
  target_url text,
  job_no text references public.install_jobs(job_no) on delete cascade,
  appointment_id uuid references public.appointments(id) on delete cascade,
  read_at timestamptz,
  dedupe_key text,
  created_at timestamptz not null default now(),
  constraint floor_notifications_one_recipient check (
    (recipient_user_id is not null)::integer +
    (recipient_technician_id is not null)::integer = 1
  )
);

create unique index if not exists floor_notifications_user_dedupe_idx
  on public.floor_notifications(recipient_user_id, dedupe_key)
  where recipient_user_id is not null and dedupe_key is not null;
create unique index if not exists floor_notifications_technician_dedupe_idx
  on public.floor_notifications(recipient_technician_id, dedupe_key)
  where recipient_technician_id is not null and dedupe_key is not null;
create index if not exists floor_notifications_user_unread_idx
  on public.floor_notifications(recipient_user_id, created_at desc) where read_at is null;
create index if not exists floor_notifications_tech_unread_idx
  on public.floor_notifications(recipient_technician_id, created_at desc) where read_at is null;

alter table public.floor_notifications enable row level security;
revoke all on public.floor_notifications from anon, authenticated;
revoke all on sequence public.floor_notifications_id_seq from anon, authenticated;
grant select, update on public.floor_notifications to authenticated;

create policy floor_notifications_read_own on public.floor_notifications for select to authenticated
  using (recipient_user_id = (select auth.uid()) and public.is_floor_staff_active());
create policy floor_notifications_update_own on public.floor_notifications for update to authenticated
  using (recipient_user_id = (select auth.uid()) and public.is_floor_staff_active())
  with check (recipient_user_id = (select auth.uid()) and public.is_floor_staff_active());

-- Web Push subscriptions. Endpoint and encryption keys are private and may
-- only be read or changed by their owner (technicians use protected RPCs).
create table if not exists public.floor_push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid references auth.users(id) on delete cascade,
  technician_id uuid references public.floor_technicians(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth_secret text not null,
  platform text not null default 'web',
  user_agent text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  constraint floor_push_one_owner check (
    (auth_user_id is not null)::integer + (technician_id is not null)::integer = 1
  )
);

alter table public.floor_push_subscriptions enable row level security;
revoke all on public.floor_push_subscriptions from anon, authenticated;
grant select, insert, update, delete on public.floor_push_subscriptions to authenticated;
create policy floor_push_staff_own on public.floor_push_subscriptions for all to authenticated
  using (auth_user_id = (select auth.uid()) and public.is_floor_staff_active())
  with check (auth_user_id = (select auth.uid()) and public.is_floor_staff_active());

create table if not exists public.floor_push_deliveries (
  id bigint generated by default as identity primary key,
  notification_id bigint not null references public.floor_notifications(id) on delete cascade,
  subscription_id uuid not null references public.floor_push_subscriptions(id) on delete cascade,
  status text not null default 'pending',
  attempts integer not null default 0,
  next_attempt_at timestamptz not null default now(),
  delivered_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  constraint floor_push_delivery_status check (status in ('pending','processing','sent','failed','expired')),
  unique(notification_id, subscription_id)
);

alter table public.floor_push_deliveries enable row level security;
revoke all on public.floor_push_deliveries from anon, authenticated;
revoke all on sequence public.floor_push_deliveries_id_seq from anon, authenticated;
create index if not exists floor_push_deliveries_pending_idx
  on public.floor_push_deliveries(status, next_attempt_at) where status in ('pending','failed');

create or replace function public.queue_floor_push_delivery()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.floor_push_deliveries(notification_id, subscription_id)
  select new.id, s.id
  from public.floor_push_subscriptions s
  where s.is_active
    and ((new.recipient_user_id is not null and s.auth_user_id = new.recipient_user_id)
      or (new.recipient_technician_id is not null and s.technician_id = new.recipient_technician_id))
  on conflict do nothing;
  return new;
end;
$$;

drop trigger if exists floor_notifications_queue_push on public.floor_notifications;
create trigger floor_notifications_queue_push after insert on public.floor_notifications
for each row execute function public.queue_floor_push_delivery();

create or replace function public.notify_floor_role(
  p_role text,
  p_event_type text,
  p_title text,
  p_body text,
  p_target_url text,
  p_job_no text,
  p_appointment_id uuid,
  p_dedupe_key text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.floor_notifications(
    recipient_user_id, event_type, title, body, target_url,
    job_no, appointment_id, dedupe_key
  )
  select p.id, p_event_type, left(p_title, 200), left(p_body, 1000),
    left(p_target_url, 500), p_job_no, p_appointment_id,
    case when p_dedupe_key is null then null else p_dedupe_key || ':' || p.id::text end
  from public.floor_staff_profiles p
  where p.is_active and p.role in (p_role, 'admin')
  on conflict do nothing;
end;
$$;

create or replace function public.notify_floor_job_transition()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare v_role text; v_title text;
begin
  if tg_op = 'UPDATE'
     and new.status is not distinct from old.status
     and new.waiting_on is not distinct from old.waiting_on
     and new.flag_note is not distinct from old.flag_note then
    return new;
  end if;
  v_role := case
    when coalesce(new.waiting_on, '') like '%ขาย%' then 'sales'
    when coalesce(new.waiting_on, '') like '%คลัง%' then 'warehouse'
    when upper(coalesce(new.waiting_on, '')) like '%CS%' then 'cs'
    else 'head_technician'
  end;
  v_title := coalesce(new.customer_name, new.job_no) || ' · ' || coalesce(new.status, 'มีการอัปเดตงาน');
  perform public.notify_floor_role(
    v_role, 'job_status_changed', v_title,
    coalesce(new.flag_note, 'สถานะงานถูกอัปเดต กรุณาเปิดใบสั่งงานเพื่อตรวจสอบ'),
    '/orders/' || new.job_no, new.job_no, null,
    'job:' || new.job_no || ':' || coalesce(new.status, '') || ':' || coalesce(new.waiting_on, '')
  );
  return new;
end;
$$;

drop trigger if exists floor_install_jobs_notify_transition on public.install_jobs;
create trigger floor_install_jobs_notify_transition
after insert or update of status, waiting_on, flag_note on public.install_jobs
for each row execute function public.notify_floor_job_transition();

create or replace function public.notify_floor_technician_assignment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare v_job_no text; v_customer text;
begin
  if not new.is_active then return new; end if;
  if tg_op = 'UPDATE' and old.technician_id = new.technician_id and old.is_active = new.is_active then
    return new;
  end if;
  select a.job_id, j.customer_name into v_job_no, v_customer
  from public.appointments a left join public.install_jobs j on j.job_no = a.job_id
  where a.id = new.appointment_id;
  insert into public.floor_notifications(
    recipient_technician_id, event_type, title, body, target_url,
    job_no, appointment_id, dedupe_key
  ) values (
    new.technician_id, 'technician_assigned',
    'ได้รับมอบหมายงานใหม่', coalesce(v_customer, v_job_no, 'เปิดตารางงานเพื่อดูรายละเอียด'),
    case when v_job_no is null then null else '/work/' ||
      (select personal_token::text from public.floor_technicians where id = new.technician_id) ||
      '?job=' || v_job_no end,
    v_job_no, new.appointment_id, 'assignment:' || new.id::text
  ) on conflict do nothing;
  return new;
end;
$$;

drop trigger if exists floor_assignment_notify_technician on public.appointment_technicians;
create trigger floor_assignment_notify_technician
after insert or update of technician_id, is_active on public.appointment_technicians
for each row execute function public.notify_floor_technician_assignment();

-- Public technician workspace detail formerly depended on broad anon SELECT.
create or replace function public.get_technician_assignment_detail(
  p_token uuid,
  p_pin text,
  p_assignment_id uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, extensions
as $$
declare v_assignment public.appointment_technicians%rowtype; v_result jsonb;
begin
  select a.* into v_assignment
  from public.appointment_technicians a
  join public.floor_technicians t on t.id = a.technician_id
  where a.id = p_assignment_id and a.is_active and t.is_active
    and t.personal_token = p_token and t.pin_hash is not null
    and extensions.crypt(regexp_replace(coalesce(p_pin, ''), '\s+', '', 'g'), t.pin_hash) = t.pin_hash;
  if v_assignment.id is null then return null; end if;

  select jsonb_build_object(
    'responsibles', coalesce((select jsonb_agg(jsonb_build_object(
      'id', x.id, 'is_lead', x.is_lead, 'first_opened_at', x.first_opened_at,
      'acknowledged_at', x.acknowledged_at,
      'technician', jsonb_build_object('name', t.name, 'phone', t.phone, 'is_team_lead', t.is_team_lead)
    ) order by x.is_lead desc, t.name)
      from public.appointment_technicians x
      join public.floor_technicians t on t.id = x.technician_id
      where x.appointment_id = v_assignment.appointment_id and x.is_active), '[]'::jsonb),
    'job', (select jsonb_build_object(
      'raw_payload', j.raw_payload, 'site_photos', j.site_photos, 'survey_data', j.survey_data
    ) from public.appointments a join public.install_jobs j on j.job_no = a.job_id
      where a.id = v_assignment.appointment_id)
  ) into v_result;
  return v_result;
end;
$$;

create or replace function public.get_technician_notifications(
  p_token uuid, p_pin text, p_limit integer default 30
)
returns jsonb
language sql
stable
security definer
set search_path = public, extensions
as $$
  select coalesce(jsonb_agg(to_jsonb(n) order by n.created_at desc), '[]'::jsonb)
  from (
    select x.id, x.event_type, x.title, x.body, x.target_url, x.job_no,
      x.appointment_id, x.read_at, x.created_at
    from public.floor_notifications x
    join public.floor_technicians t on t.id = x.recipient_technician_id
    where t.personal_token = p_token and t.is_active and t.pin_hash is not null
      and extensions.crypt(regexp_replace(coalesce(p_pin, ''), '\s+', '', 'g'), t.pin_hash) = t.pin_hash
    order by x.created_at desc limit greatest(1, least(coalesce(p_limit, 30), 100))
  ) n;
$$;

create or replace function public.mark_technician_notification_read(
  p_token uuid, p_pin text, p_notification_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  update public.floor_notifications n set read_at = coalesce(read_at, now())
  from public.floor_technicians t
  where n.id = p_notification_id and t.id = n.recipient_technician_id
    and t.personal_token = p_token and t.is_active and t.pin_hash is not null
    and extensions.crypt(regexp_replace(coalesce(p_pin, ''), '\s+', '', 'g'), t.pin_hash) = t.pin_hash;
  return found;
end;
$$;

create or replace function public.register_technician_push_subscription(
  p_token uuid, p_pin text, p_endpoint text, p_p256dh text,
  p_auth_secret text, p_platform text, p_user_agent text
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare v_technician_id uuid;
begin
  select t.id into v_technician_id from public.floor_technicians t
  where t.personal_token = p_token and t.is_active and t.pin_hash is not null
    and extensions.crypt(regexp_replace(coalesce(p_pin, ''), '\s+', '', 'g'), t.pin_hash) = t.pin_hash;
  if v_technician_id is null then raise exception 'technician authentication required'; end if;
  insert into public.floor_push_subscriptions(
    technician_id, endpoint, p256dh, auth_secret, platform, user_agent
  ) values (
    v_technician_id, left(p_endpoint, 2000), left(p_p256dh, 500), left(p_auth_secret, 500),
    left(coalesce(p_platform, 'web'), 50), left(coalesce(p_user_agent, ''), 500)
  ) on conflict(endpoint) do update set
    auth_user_id = null, technician_id = excluded.technician_id,
    p256dh = excluded.p256dh, auth_secret = excluded.auth_secret,
    platform = excluded.platform, user_agent = excluded.user_agent,
    is_active = true, updated_at = now(), last_seen_at = now();
  return true;
end;
$$;

revoke all on function public.queue_floor_push_delivery() from public, anon, authenticated;
revoke all on function public.notify_floor_role(text,text,text,text,text,text,uuid,text) from public, anon, authenticated;
revoke all on function public.notify_floor_job_transition() from public, anon, authenticated;
revoke all on function public.notify_floor_technician_assignment() from public, anon, authenticated;
revoke all on function public.get_technician_assignment_detail(uuid,text,uuid) from public, anon, authenticated;
revoke all on function public.get_technician_notifications(uuid,text,integer) from public, anon, authenticated;
revoke all on function public.mark_technician_notification_read(uuid,text,bigint) from public, anon, authenticated;
revoke all on function public.register_technician_push_subscription(uuid,text,text,text,text,text,text) from public, anon, authenticated;
grant execute on function public.get_technician_assignment_detail(uuid,text,uuid) to anon, authenticated;
grant execute on function public.get_technician_notifications(uuid,text,integer) to anon, authenticated;
grant execute on function public.mark_technician_notification_read(uuid,text,bigint) to anon, authenticated;
grant execute on function public.register_technician_push_subscription(uuid,text,text,text,text,text,text) to anon, authenticated;

-- Realtime delivers only rows that pass RLS for the signed-in employee.
do $$ begin
  alter publication supabase_realtime add table public.floor_notifications;
exception when duplicate_object then null;
end $$;

notify pgrst, 'reload schema';
