-- Background GPS tracking for FloorNow technician mobile app.
-- Raw coordinates are never exposed to anon table access. All mobile/customer
-- access is capability-scoped through RPC functions.

alter table public.floor_technicians
  add column if not exists auth_user_id uuid unique references auth.users(id) on delete set null;

create table public.floor_job_materials (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null unique references public.appointments(id) on delete restrict,
  planned_sheet_count integer not null default 0,
  planned_by text not null default 'หัวหน้าช่าง',
  planned_at timestamptz not null default now(),
  picked_sheet_count integer,
  picked_by_technician_id uuid references public.floor_technicians(id) on delete restrict,
  picked_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint floor_job_materials_planned_nonnegative check (planned_sheet_count >= 0),
  constraint floor_job_materials_picked_nonnegative check (picked_sheet_count is null or picked_sheet_count >= 0)
);

create table public.floor_technician_devices (
  id uuid primary key default gen_random_uuid(),
  technician_id uuid not null references public.floor_technicians(id) on delete restrict,
  device_token uuid not null default gen_random_uuid() unique,
  platform text not null,
  device_name text,
  app_version text,
  background_permission text not null default 'unknown',
  is_active boolean not null default true,
  enrolled_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  constraint floor_technician_devices_platform_check check (platform in ('android', 'ios')),
  constraint floor_technician_devices_permission_check
    check (background_permission in ('unknown', 'denied', 'foreground', 'always'))
);

create index floor_technician_devices_technician_active_idx
  on public.floor_technician_devices(technician_id, is_active, last_seen_at desc);

create table public.floor_tracking_sessions (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null references public.appointments(id) on delete restrict,
  assignment_id uuid not null references public.appointment_technicians(id) on delete restrict,
  technician_id uuid not null references public.floor_technicians(id) on delete restrict,
  device_id uuid not null references public.floor_technician_devices(id) on delete restrict,
  customer_token uuid not null default gen_random_uuid() unique,
  status text not null default 'travelling',
  destination_latitude double precision,
  destination_longitude double precision,
  latest_latitude double precision,
  latest_longitude double precision,
  latest_accuracy_m double precision,
  latest_captured_at timestamptz,
  distance_meters integer,
  eta_minutes integer,
  eta_updated_at timestamptz,
  sharing_started_at timestamptz not null default now(),
  sharing_ended_at timestamptz,
  customer_access_expires_at timestamptz not null,
  customer_signed_name text,
  customer_signature_path text,
  customer_signed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint floor_tracking_sessions_status_check
    check (status in ('travelling', 'arrived', 'installing', 'completed', 'cancelled')),
  constraint floor_tracking_sessions_destination_lat_check
    check (destination_latitude is null or destination_latitude between -90 and 90),
  constraint floor_tracking_sessions_destination_lng_check
    check (destination_longitude is null or destination_longitude between -180 and 180),
  constraint floor_tracking_sessions_latest_lat_check
    check (latest_latitude is null or latest_latitude between -90 and 90),
  constraint floor_tracking_sessions_latest_lng_check
    check (latest_longitude is null or latest_longitude between -180 and 180),
  constraint floor_tracking_sessions_distance_check
    check (distance_meters is null or distance_meters >= 0),
  constraint floor_tracking_sessions_eta_check
    check (eta_minutes is null or eta_minutes >= 0)
);

create unique index floor_tracking_sessions_one_active_per_appointment_idx
  on public.floor_tracking_sessions(appointment_id)
  where sharing_ended_at is null;

create index floor_tracking_sessions_assignment_time_idx
  on public.floor_tracking_sessions(assignment_id, created_at desc);

create index floor_tracking_sessions_customer_token_idx
  on public.floor_tracking_sessions(customer_token);

create table public.floor_location_points (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.floor_tracking_sessions(id) on delete restrict,
  technician_id uuid not null references public.floor_technicians(id) on delete restrict,
  device_id uuid not null references public.floor_technician_devices(id) on delete restrict,
  latitude double precision not null,
  longitude double precision not null,
  accuracy_m double precision,
  speed_mps double precision,
  heading_deg double precision,
  captured_at timestamptz not null,
  received_at timestamptz not null default now(),
  constraint floor_location_points_lat_check check (latitude between -90 and 90),
  constraint floor_location_points_lng_check check (longitude between -180 and 180),
  constraint floor_location_points_accuracy_check check (accuracy_m is null or accuracy_m >= 0),
  constraint floor_location_points_speed_check check (speed_mps is null or speed_mps >= 0),
  constraint floor_location_points_heading_check check (heading_deg is null or heading_deg between 0 and 360)
);

create index floor_location_points_session_captured_idx
  on public.floor_location_points(session_id, captured_at desc);

create table public.floor_job_status_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.floor_tracking_sessions(id) on delete restrict,
  assignment_id uuid not null references public.appointment_technicians(id) on delete restrict,
  technician_id uuid not null references public.floor_technicians(id) on delete restrict,
  status text not null,
  note text,
  photo_paths text[] not null default '{}',
  latitude double precision,
  longitude double precision,
  occurred_at timestamptz not null default now(),
  constraint floor_job_status_events_status_check
    check (status in ('travelling', 'arrived', 'installing', 'completed', 'customer_signed', 'cancelled')),
  constraint floor_job_status_events_lat_check check (latitude is null or latitude between -90 and 90),
  constraint floor_job_status_events_lng_check check (longitude is null or longitude between -180 and 180)
);

create index floor_job_status_events_session_time_idx
  on public.floor_job_status_events(session_id, occurred_at);

alter table public.floor_job_materials enable row level security;
alter table public.floor_technician_devices enable row level security;
alter table public.floor_tracking_sessions enable row level security;
alter table public.floor_location_points enable row level security;
alter table public.floor_job_status_events enable row level security;

revoke all on public.floor_job_materials from anon, authenticated;

revoke all on public.floor_technician_devices from anon, authenticated;
revoke all on public.floor_tracking_sessions from anon, authenticated;
revoke all on public.floor_location_points from anon, authenticated;
revoke all on public.floor_job_status_events from anon, authenticated;
revoke all on sequence public.floor_location_points_id_seq from anon, authenticated;
revoke all on sequence public.floor_job_status_events_id_seq from anon, authenticated;

create or replace function public.register_floor_technician_device(
  p_personal_token uuid,
  p_platform text,
  p_device_name text default null,
  p_app_version text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_technician public.floor_technicians%rowtype;
  v_device public.floor_technician_devices%rowtype;
begin
  if (select auth.uid()) is null then
    raise exception 'authentication required';
  end if;
  if p_platform not in ('android', 'ios') then
    raise exception 'unsupported platform';
  end if;

  select * into v_technician
  from public.floor_technicians
  where personal_token = p_personal_token
    and is_active = true;

  if v_technician.id is null then
    raise exception 'invalid technician token';
  end if;

  if v_technician.auth_user_id is not null
     and v_technician.auth_user_id <> (select auth.uid()) then
    raise exception 'technician account is already claimed';
  end if;

  update public.floor_technicians
  set auth_user_id = (select auth.uid()),
      updated_at = now()
  where id = v_technician.id
    and (auth_user_id is null or auth_user_id = (select auth.uid()));

  insert into public.floor_technician_devices(
    technician_id, platform, device_name, app_version
  ) values (
    v_technician.id,
    p_platform,
    nullif(left(btrim(coalesce(p_device_name, '')), 120), ''),
    nullif(left(btrim(coalesce(p_app_version, '')), 40), '')
  )
  returning * into v_device;

  return jsonb_build_object(
    'deviceId', v_device.id,
    'deviceToken', v_device.device_token,
    'technicianId', v_technician.id,
    'technicianName', v_technician.name
  );
end;
$$;

create or replace function public.update_floor_device_permission(
  p_device_token uuid,
  p_permission text,
  p_app_version text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if (select auth.uid()) is null then
    return false;
  end if;
  if p_permission not in ('unknown', 'denied', 'foreground', 'always') then
    return false;
  end if;

  update public.floor_technician_devices d
  set background_permission = p_permission,
      app_version = coalesce(nullif(left(btrim(coalesce(p_app_version, '')), 40), ''), app_version),
      last_seen_at = now()
  from public.floor_technicians t
  where d.device_token = p_device_token
    and d.is_active = true
    and t.id = d.technician_id
    and t.auth_user_id = (select auth.uid());

  return found;
end;
$$;

create or replace function public.get_floor_mobile_workspace(p_device_token uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'device', jsonb_build_object(
      'id', d.id,
      'platform', d.platform,
      'backgroundPermission', d.background_permission
    ),
    'technician', jsonb_build_object(
      'id', t.id,
      'name', t.name,
      'teamId', t.team_id,
      'teamName', team.name,
      'isTeamLead', t.is_team_lead
    ),
    'assignments', coalesce((
      select jsonb_agg(jsonb_build_object(
        'assignmentId', a.id,
        'appointmentId', ap.id,
        'isLead', a.is_lead,
        'acknowledgedAt', a.acknowledged_at,
        'slotStart', ap.slot_start,
        'slotEnd', ap.slot_end,
        'appointmentStatus', ap.status,
        'teamName', ap_team.name,
        'notes', ap.notes,
        'requirement', ap.requirement,
        'jobNo', j.job_no,
        'source', j.source,
        'billNo', j.bill_no,
        'customerName', j.customer_name,
        'customerPhone', j.customer_phone,
        'address', j.address,
        'locationUrl', j.location_url,
        'productName', j.product_name,
        'sitePhotos', j.site_photos,
        'rawPayload', j.raw_payload,
        'plannedSheetCount', material.planned_sheet_count,
        'pickedSheetCount', material.picked_sheet_count,
        'trackingSession', case when tracking.id is null then null else jsonb_build_object(
          'id', tracking.id,
          'status', tracking.status,
          'customerToken', tracking.customer_token,
          'sharingStartedAt', tracking.sharing_started_at,
          'latestCapturedAt', tracking.latest_captured_at
        ) end
      ) order by ap.slot_start)
      from public.appointment_technicians a
      join public.appointments ap on ap.id = a.appointment_id
      left join public.tech_teams ap_team on ap_team.id = ap.tech_id
      left join public.install_jobs j on j.job_no = ap.job_id
      left join public.floor_job_materials material on material.appointment_id = ap.id
      left join lateral (
        select s.*
        from public.floor_tracking_sessions s
        where s.appointment_id = ap.id
        order by s.created_at desc
        limit 1
      ) tracking on true
      where a.technician_id = t.id
        and a.is_active = true
        and ap.status <> 'cancelled'
        and ap.slot_end >= now() - interval '12 hours'
    ), '[]'::jsonb)
  )
  from public.floor_technician_devices d
  join public.floor_technicians t on t.id = d.technician_id
  left join public.tech_teams team on team.id = t.team_id
  where d.device_token = p_device_token
    and d.is_active = true
    and t.auth_user_id = (select auth.uid())
    and t.is_active = true;
$$;

create or replace function public.set_floor_job_material_plan(
  p_appointment_id uuid,
  p_planned_sheet_count integer,
  p_planned_by text default 'หัวหน้าช่าง'
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if (select auth.uid()) is null or p_planned_sheet_count < 0 then
    return false;
  end if;

  if not exists (
    select 1
    from public.floor_technicians t
    where t.auth_user_id = (select auth.uid())
      and t.is_active = true
      and t.is_team_lead = true
  ) then
    raise exception 'team lead permission required';
  end if;

  if not exists (
    select 1 from public.appointments ap
    where ap.id = p_appointment_id and ap.status <> 'cancelled'
  ) then
    return false;
  end if;

  insert into public.floor_job_materials(
    appointment_id, planned_sheet_count, planned_by, planned_at, updated_at
  ) values (
    p_appointment_id,
    p_planned_sheet_count,
    coalesce(nullif(left(btrim(coalesce(p_planned_by, '')), 120), ''), 'หัวหน้าช่าง'),
    now(),
    now()
  )
  on conflict (appointment_id) do update
    set planned_sheet_count = excluded.planned_sheet_count,
        planned_by = excluded.planned_by,
        planned_at = excluded.planned_at,
        updated_at = excluded.updated_at;

  return true;
end;
$$;

create or replace function public.start_floor_tracking(
  p_device_token uuid,
  p_assignment_id uuid,
  p_picked_sheet_count integer,
  p_destination_latitude double precision,
  p_destination_longitude double precision,
  p_photo_paths text[]
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_device public.floor_technician_devices%rowtype;
  v_assignment public.appointment_technicians%rowtype;
  v_appointment public.appointments%rowtype;
  v_session public.floor_tracking_sessions%rowtype;
begin
  if p_picked_sheet_count is null or p_picked_sheet_count < 0 then
    raise exception 'picked sheet count is required';
  end if;
  if p_destination_latitude not between -90 and 90
     or p_destination_longitude not between -180 and 180 then
    raise exception 'invalid destination';
  end if;
  if coalesce(cardinality(p_photo_paths), 0) = 0 then
    raise exception 'status photo is required';
  end if;

  select d.* into v_device
  from public.floor_technician_devices d
  join public.floor_technicians t on t.id = d.technician_id
  where d.device_token = p_device_token
    and d.is_active = true
    and d.background_permission = 'always'
    and t.auth_user_id = (select auth.uid());

  if v_device.id is null then
    raise exception 'device is not authorized for background location';
  end if;

  select * into v_assignment
  from public.appointment_technicians
  where id = p_assignment_id
    and technician_id = v_device.technician_id
    and is_active = true;

  if v_assignment.id is null then
    raise exception 'assignment not found';
  end if;

  select * into v_appointment
  from public.appointments
  where id = v_assignment.appointment_id
    and status <> 'cancelled';

  if v_appointment.id is null then
    raise exception 'appointment not available';
  end if;

  insert into public.floor_job_materials(
    appointment_id, planned_sheet_count, picked_sheet_count,
    picked_by_technician_id, picked_at, updated_at
  ) values (
    v_appointment.id, 0, p_picked_sheet_count,
    v_device.technician_id, now(), now()
  )
  on conflict (appointment_id) do update
    set picked_sheet_count = excluded.picked_sheet_count,
        picked_by_technician_id = excluded.picked_by_technician_id,
        picked_at = excluded.picked_at,
        updated_at = excluded.updated_at;

  select * into v_session
  from public.floor_tracking_sessions
  where appointment_id = v_appointment.id
    and sharing_ended_at is null
  limit 1;

  if v_session.id is null then
    insert into public.floor_tracking_sessions(
      appointment_id, assignment_id, technician_id, device_id,
      destination_latitude, destination_longitude,
      customer_access_expires_at
    ) values (
      v_appointment.id, v_assignment.id, v_device.technician_id, v_device.id,
      p_destination_latitude, p_destination_longitude,
      greatest(v_appointment.slot_end + interval '12 hours', now() + interval '12 hours')
    ) returning * into v_session;
  elsif v_session.technician_id <> v_device.technician_id then
    raise exception 'another technician is already sharing this job';
  end if;

  insert into public.floor_job_status_events(
    session_id, assignment_id, technician_id, status, photo_paths
  ) values (
    v_session.id, v_assignment.id, v_device.technician_id, 'travelling', p_photo_paths
  );

  update public.floor_technician_devices
  set last_seen_at = now()
  where id = v_device.id;

  return jsonb_build_object(
    'sessionId', v_session.id,
    'customerToken', v_session.customer_token,
    'status', v_session.status
  );
end;
$$;

create or replace function public.record_floor_location_batch(
  p_device_token uuid,
  p_session_id uuid,
  p_points jsonb
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_device public.floor_technician_devices%rowtype;
  v_session public.floor_tracking_sessions%rowtype;
  v_count integer;
  v_latest record;
begin
  if jsonb_typeof(p_points) <> 'array' then
    raise exception 'points must be an array';
  end if;
  v_count := jsonb_array_length(p_points);
  if v_count < 1 or v_count > 50 then
    raise exception 'point batch must contain 1 to 50 items';
  end if;

  select d.* into v_device
  from public.floor_technician_devices d
  join public.floor_technicians t on t.id = d.technician_id
  where d.device_token = p_device_token
    and d.is_active = true
    and t.auth_user_id = (select auth.uid());

  select * into v_session
  from public.floor_tracking_sessions
  where id = p_session_id
    and device_id = v_device.id
    and technician_id = v_device.technician_id
    and sharing_ended_at is null;

  if v_session.id is null then
    raise exception 'active tracking session not found';
  end if;

  insert into public.floor_location_points(
    session_id, technician_id, device_id, latitude, longitude,
    accuracy_m, speed_mps, heading_deg, captured_at
  )
  select
    v_session.id,
    v_device.technician_id,
    v_device.id,
    (point->>'latitude')::double precision,
    (point->>'longitude')::double precision,
    nullif(point->>'accuracy', '')::double precision,
    nullif(point->>'speed', '')::double precision,
    nullif(point->>'heading', '')::double precision,
    coalesce(nullif(point->>'capturedAt', '')::timestamptz, now())
  from jsonb_array_elements(p_points) point;

  select latitude, longitude, accuracy_m, captured_at
  into v_latest
  from public.floor_location_points
  where session_id = v_session.id
  order by captured_at desc
  limit 1;

  update public.floor_tracking_sessions
  set latest_latitude = v_latest.latitude,
      latest_longitude = v_latest.longitude,
      latest_accuracy_m = v_latest.accuracy_m,
      latest_captured_at = v_latest.captured_at,
      updated_at = now()
  where id = v_session.id;

  update public.floor_technician_devices
  set last_seen_at = now()
  where id = v_device.id;

  return v_count;
end;
$$;

create or replace function public.record_floor_job_status(
  p_device_token uuid,
  p_session_id uuid,
  p_status text,
  p_photo_paths text[],
  p_note text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_device public.floor_technician_devices%rowtype;
  v_session public.floor_tracking_sessions%rowtype;
begin
  if p_status not in ('arrived', 'installing', 'completed', 'cancelled') then
    return false;
  end if;
  if p_status <> 'cancelled' and coalesce(cardinality(p_photo_paths), 0) = 0 then
    raise exception 'status photo is required';
  end if;

  select d.* into v_device
  from public.floor_technician_devices d
  join public.floor_technicians t on t.id = d.technician_id
  where d.device_token = p_device_token
    and d.is_active = true
    and t.auth_user_id = (select auth.uid());

  select * into v_session
  from public.floor_tracking_sessions
  where id = p_session_id
    and device_id = v_device.id
    and sharing_ended_at is null;

  if v_session.id is null then
    return false;
  end if;

  insert into public.floor_job_status_events(
    session_id, assignment_id, technician_id, status, note, photo_paths,
    latitude, longitude
  ) values (
    v_session.id, v_session.assignment_id, v_session.technician_id,
    p_status, nullif(left(btrim(coalesce(p_note, '')), 1000), ''), p_photo_paths,
    v_session.latest_latitude, v_session.latest_longitude
  );

  update public.floor_tracking_sessions
  set status = p_status,
      sharing_ended_at = case when p_status = 'cancelled' then now() else sharing_ended_at end,
      updated_at = now()
  where id = v_session.id;

  return true;
end;
$$;

create or replace function public.record_floor_customer_signature(
  p_device_token uuid,
  p_session_id uuid,
  p_signer_name text,
  p_signature_path text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_device public.floor_technician_devices%rowtype;
  v_session public.floor_tracking_sessions%rowtype;
begin
  if nullif(btrim(coalesce(p_signer_name, '')), '') is null
     or nullif(btrim(coalesce(p_signature_path, '')), '') is null then
    raise exception 'signer name and signature are required';
  end if;

  select d.* into v_device
  from public.floor_technician_devices d
  join public.floor_technicians t on t.id = d.technician_id
  where d.device_token = p_device_token
    and d.is_active = true
    and t.auth_user_id = (select auth.uid());

  select * into v_session
  from public.floor_tracking_sessions
  where id = p_session_id
    and device_id = v_device.id
    and sharing_ended_at is null
    and status = 'completed';

  if v_session.id is null then
    return false;
  end if;

  update public.floor_tracking_sessions
  set customer_signed_name = left(btrim(p_signer_name), 160),
      customer_signature_path = left(btrim(p_signature_path), 1000),
      customer_signed_at = now(),
      sharing_ended_at = now(),
      updated_at = now()
  where id = v_session.id;

  insert into public.floor_job_status_events(
    session_id, assignment_id, technician_id, status, note, photo_paths
  ) values (
    v_session.id, v_session.assignment_id, v_session.technician_id,
    'customer_signed', left(btrim(p_signer_name), 160), '{}'
  );

  return true;
end;
$$;

create or replace function public.set_floor_tracking_eta(
  p_device_token uuid,
  p_session_id uuid,
  p_distance_meters integer,
  p_eta_minutes integer
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_distance_meters < 0 or p_eta_minutes < 0 then
    return false;
  end if;

  update public.floor_tracking_sessions s
  set distance_meters = p_distance_meters,
      eta_minutes = p_eta_minutes,
      eta_updated_at = now(),
      updated_at = now()
  from public.floor_technician_devices d
  join public.floor_technicians t on t.id = d.technician_id
  where s.id = p_session_id
    and s.device_id = d.id
    and d.device_token = p_device_token
    and d.is_active = true
    and t.auth_user_id = (select auth.uid())
    and s.sharing_ended_at is null;

  return found;
end;
$$;

create or replace function public.get_floor_customer_tracking(p_customer_token uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'jobNo', j.job_no,
    'customerName', j.customer_name,
    'appointmentStart', ap.slot_start,
    'appointmentEnd', ap.slot_end,
    'teamName', team.name,
    'technicianName', tech.name,
    'status', s.status,
    'distanceMeters', s.distance_meters,
    'etaMinutes', s.eta_minutes,
    'etaUpdatedAt', s.eta_updated_at,
    'locationUpdatedAt', s.latest_captured_at,
    'sharingEndedAt', s.sharing_ended_at,
    'customerSignedAt', s.customer_signed_at,
    'events', coalesce((
      select jsonb_agg(jsonb_build_object(
        'status', e.status,
        'note', e.note,
        'photoPaths', e.photo_paths,
        'occurredAt', e.occurred_at
      ) order by e.occurred_at)
      from public.floor_job_status_events e
      where e.session_id = s.id
    ), '[]'::jsonb)
  )
  from public.floor_tracking_sessions s
  join public.appointments ap on ap.id = s.appointment_id
  left join public.install_jobs j on j.job_no = ap.job_id
  left join public.tech_teams team on team.id = ap.tech_id
  join public.floor_technicians tech on tech.id = s.technician_id
  where s.customer_token = p_customer_token
    and s.customer_access_expires_at > now();
$$;

revoke all on function public.register_floor_technician_device(uuid, text, text, text) from public, anon, authenticated;
revoke all on function public.update_floor_device_permission(uuid, text, text) from public, anon, authenticated;
revoke all on function public.get_floor_mobile_workspace(uuid) from public, anon, authenticated;
revoke all on function public.set_floor_job_material_plan(uuid, integer, text) from public, anon, authenticated;
revoke all on function public.start_floor_tracking(uuid, uuid, integer, double precision, double precision, text[]) from public, anon, authenticated;
revoke all on function public.record_floor_location_batch(uuid, uuid, jsonb) from public, anon, authenticated;
revoke all on function public.record_floor_job_status(uuid, uuid, text, text[], text) from public, anon, authenticated;
revoke all on function public.record_floor_customer_signature(uuid, uuid, text, text) from public, anon, authenticated;
revoke all on function public.set_floor_tracking_eta(uuid, uuid, integer, integer) from public, anon, authenticated;
revoke all on function public.get_floor_customer_tracking(uuid) from public, anon, authenticated;

grant execute on function public.register_floor_technician_device(uuid, text, text, text) to authenticated;
grant execute on function public.update_floor_device_permission(uuid, text, text) to authenticated;
grant execute on function public.get_floor_mobile_workspace(uuid) to authenticated;
grant execute on function public.set_floor_job_material_plan(uuid, integer, text) to authenticated;
grant execute on function public.start_floor_tracking(uuid, uuid, integer, double precision, double precision, text[]) to authenticated;
grant execute on function public.record_floor_location_batch(uuid, uuid, jsonb) to authenticated;
grant execute on function public.record_floor_job_status(uuid, uuid, text, text[], text) to authenticated;
grant execute on function public.record_floor_customer_signature(uuid, uuid, text, text) to authenticated;
grant execute on function public.set_floor_tracking_eta(uuid, uuid, integer, integer) to authenticated;
grant execute on function public.get_floor_customer_tracking(uuid) to anon, authenticated;

comment on table public.floor_job_materials is
  'Floor-owned planned and actually picked sheet counts per installation appointment.';
comment on table public.floor_technician_devices is
  'Floor-owned enrolled mobile devices. device_token is a private capability credential.';
comment on table public.floor_tracking_sessions is
  'Floor-owned background GPS sessions. Raw current coordinates are internal-only.';
comment on table public.floor_location_points is
  'Floor-owned raw GPS history. No direct anon or authenticated Data API access.';
comment on table public.floor_job_status_events is
  'Floor-owned append-only job status and photo evidence timeline.';
